{
 "openapi": "3.0.0",
 "servers": [
  {
   "url": "https://cloudsearch.googleapis.com/"
  }
 ],
 "info": {
  "contact": {
   "name": "Google",
   "url": "https://google.com",
   "x-twitter": "youtube"
  },
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "license": {
   "name": "Creative Commons Attribution 3.0",
   "url": "http://creativecommons.org/licenses/by/3.0/"
  },
  "termsOfService": "https://developers.google.com/terms/",
  "title": "Cloud Search API",
  "version": "v1",
  "x-apisguru-categories": [
   "analytics",
   "media"
  ],
  "x-logo": {
   "url": "https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_%282013-2017%29.svg"
  },
  "x-origin": [
   {
    "converter": {
     "url": "https://github.com/mermade/oas-kit",
     "version": "7.0.4"
    },
    "format": "google",
    "url": "https://cloudsearch.googleapis.com/$discovery/rest?version=v1",
    "version": "v1"
   }
  ],
  "x-providerName": "googleapis.com",
  "x-serviceName": "cloudsearch"
 },
 "tags": [
  {
   "name": "debug"
  },
  {
   "name": "indexing"
  },
  {
   "name": "media"
  },
  {
   "name": "operations"
  },
  {
   "name": "query"
  },
  {
   "name": "settings"
  },
  {
   "name": "stats"
  },
  {
   "name": "v1"
  }
 ],
 "paths": {
  "/v1/debug/{name}/items:searchByViewUrl": {
   "post": {
    "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.debug.datasources.items.searchByViewUrl",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     }
    ],
    "tags": [
     "debug"
    ]
   }
  },
  "/v1/debug/{name}:checkAccess": {
   "post": {
    "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.debug.datasources.items.checkAccess",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     }
    ],
    "tags": [
     "debug"
    ]
   }
  },
  "/v1/debug/{parent}/items:forunmappedidentity": {
   "get": {
    "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.debug.identitysources.items.listForunmappedidentity",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     }
    ],
    "tags": [
     "debug"
    ]
   }
  },
  "/v1/debug/{parent}/unmappedids": {
   "get": {
    "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.debug.identitysources.unmappedids.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     }
    ],
    "tags": [
     "debug"
    ]
   }
  },
  "/v1/indexing/{name}": {
   "delete": {
    "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.delete",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   },
   "get": {
    "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}/items": {
   "get": {
    "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}/items:deleteQueueItems": {
   "post": {
    "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.deleteQueueItems",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}/items:poll": {
   "post": {
    "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push with the type REQ[...]",
    "operationId": "cloudsearch.indexing.datasources.items.poll",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}/items:unreserve": {
   "post": {
    "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.unreserve",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}/schema": {
   "delete": {
    "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
    "operationId": "cloudsearch.indexing.datasources.deleteSchema",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   },
   "get": {
    "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute.",
    "operationId": "cloudsearch.indexing.datasources.getSchema",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   },
   "put": {
    "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
    "operationId": "cloudsearch.indexing.datasources.updateSchema",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}:index": {
   "post": {
    "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.index",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}:push": {
   "post": {
    "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.push",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/indexing/{name}:upload": {
   "post": {
    "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
    "operationId": "cloudsearch.indexing.datasources.items.upload",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "indexing"
    ]
   }
  },
  "/v1/media/{resourceName}": {
   "post": {
    "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the content, as a strea[...]",
    "operationId": "cloudsearch.media.upload",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     }
    ],
    "tags": [
     "media"
    ]
   }
  },
  "/v1/query/search": {
   "post": {
    "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delega[...]",
    "operationId": "cloudsearch.query.search",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ]
     }
    ],
    "tags": [
     "query"
    ]
   }
  },
  "/v1/query/sources": {
   "get": {
    "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
    "operationId": "cloudsearch.query.sources.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ]
     }
    ],
    "tags": [
     "query"
    ]
   }
  },
  "/v1/query/suggest": {
   "post": {
    "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/cloud-search/docs/guides/delegation/).",
    "operationId": "cloudsearch.query.suggest",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.query"
      ]
     }
    ],
    "tags": [
     "query"
    ]
   }
  },
  "/v1/settings/customer": {
   "get": {
    "description": "Get customer settings. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.getCustomer",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "patch": {
    "description": "Update customer settings. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.updateCustomer",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   }
  },
  "/v1/settings/datasources": {
   "get": {
    "description": "Lists datasources. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.datasources.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "post": {
    "description": "Creates a datasource. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.datasources.create",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   }
  },
  "/v1/settings/searchapplications": {
   "get": {
    "description": "Lists all search applications. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "post": {
    "description": "Creates a search application. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.create",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   }
  },
  "/v1/settings/{name}": {
   "delete": {
    "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.delete",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "get": {
    "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "patch": {
    "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.patch",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   },
   "put": {
    "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.update",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   }
  },
  "/v1/settings/{name}:reset": {
   "post": {
    "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.settings.searchapplications.reset",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "settings"
    ]
   }
  },
  "/v1/stats/index": {
   "get": {
    "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.getIndex",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/index/{name}": {
   "get": {
    "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.index.datasources.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/query": {
   "get": {
    "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.getQuery",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/query/{name}": {
   "get": {
    "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.query.searchapplications.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/searchapplication": {
   "get": {
    "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.getSearchapplication",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/session": {
   "get": {
    "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.getSession",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/session/{name}": {
   "get": {
    "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.session.searchapplications.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/user": {
   "get": {
    "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.getUser",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/stats/user/{name}": {
   "get": {
    "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
    "operationId": "cloudsearch.stats.user.searchapplications.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.stats.indexing"
      ]
     }
    ],
    "tags": [
     "stats"
    ]
   }
  },
  "/v1/{name}": {
   "get": {
    "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
    "operationId": "cloudsearch.operations.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "operations"
    ]
   }
  },
  "/v1/{name}/lro": {
   "get": {
    "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operations col[...]",
    "operationId": "cloudsearch.operations.lro.list",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.debug"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.indexing"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.query"
      ]
     }
    ],
    "tags": [
     "operations"
    ]
   }
  },
  "/v1:initializeCustomer": {
   "post": {
    "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute.",
    "operationId": "cloudsearch.initializeCustomer",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/cloud_search.settings.indexing"
      ]
     }
    ],
    "tags": [
     "v1"
    ]
   }
  }
 },
 "components": {
  "schemas": {
   "AbuseReportingConfig": {
    "description": "Abuse reporting configuration outlining what is supported in this conference.",
    "properties": {
     "recordingAllowed": {
      "description": "Whether the current call may include video recordings in its abuse reports.",
      "type": "boolean"
     },
     "writtenUgcAllowed": {
      "description": "Whether the current call may include user generated content (chat, polls, Q&A...) in its abuse reports.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AckInfo": {
    "description": "Information about how devices in a meeting have acked for a session/operation.",
    "properties": {
     "unackedDeviceCount": {
      "description": "Output only. Number of meeting devices that have not acked yet.",
      "format": "int32",
      "readOnly": true,
      "type": "integer"
     },
     "unackedDeviceIds": {
      "description": "Output only. IDs of meeting devices (at most ten are provided) that have not acked yet.",
      "items": {
       "type": "string"
      },
      "readOnly": true,
      "type": "array"
     }
    },
    "type": "object"
   },
   "AclFixRequest": {
    "description": "The request set by clients to instruct Backend how the user intend to fix the ACL. Technically it's not a request to ACL Fixer, because Backend uses /DriveService.Share to modify Drive ACLs.",
    "properties": {
     "recipientEmails": {
      "description": "For Spaces messages: This field is ignored. For DMs messages: The list of email addresses that should be added to the Drive item's ACL. In general, the list should not be empty when the boolean \"should_fix\" field is set; otherwise, the list should be empty. During transition - when clients do not specify this field but the \"should_fix\" is true, we follow the legacy behavior: share to all users in the DM regardless of emails. This behavior is being phased out.",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "role": {
      "enum": [
       "UNKNOWN",
       "READER",
       "COMMENTER",
       "WRITER"
      ],
      "type": "string"
     },
     "shouldFix": {
      "description": "Whether to attempt to fix the ACL by adding the room or DM members to the Drive file's ACL.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AclFixStatus": {
    "description": "The message reconstructed based on information in the response of /PermissionFixOptionsService.Query (or the Apiary API that wraps it). Indicates the ability of the requester to change the access to the Drive file for the room roster or the DM members. Used in GetMessagePreviewMetadataResponse only.",
    "properties": {
     "fixability": {
      "enum": [
       "UNKNOWN",
       "ALREADY_ACCESSIBLE",
       "CAN_FIX",
       "CANNOT_FIX",
       "ACL_FIXER_ERROR"
      ],
      "type": "string"
     },
     "fixableEmailAddress": {
      "description": "List of recipient email addresses for which access can be granted. This field contains the same email addresses from the GetMessagePreviewMetadata request if all recipients can be successfully added to the ACL as determined by Drive ACL Fixer. For now, the field is non-empty if and only if the \"fixability\" value is \"CAN_FIX\".",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "outOfDomainWarningEmailAddress": {
      "description": "List of recipient email addresses for which an out-of-domain-sharing warning must be shown, stating that these email addresses are not in the Google Apps organization that the requested item belong to. Empty if all recipients are in the same Google Apps organization.",
      "items": {
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AclInfo": {
    "description": "Next tag: 4",
    "properties": {
     "groupsCount": {
      "description": "Number of groups which have at least read access to the document.",
      "format": "int32",
      "type": "integer"
     },
     "scope": {
      "description": "The scope to which the content was shared.",
      "enum": [
       "LIMITED",
       "DASHER_DOMAIN_WITH_LINK",
       "DASHER_DOMAIN",
       "PUBLIC_WITH_LINK",
       "PUBLIC",
       "TEAM_DRIVE"
      ],
      "type": "string"
     },
     "usersCount": {
      "description": "Number of users which have at least read access to the document.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "ActionParameter": {
    "description": "List of string parameters that developers can specify when the above action method (in apps script) is invoked. An example use case is for 3 snooze buttons: snooze now, snooze 1 day, snooze next week. Developers can have action method = snooze() and pass the snooze type and snooze time in list of string parameters.",
    "properties": {
     "key": {
      "type": "string"
     },
     "value": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "AddonComposeUiActionMarkup": {
    "properties": {
     "type": {
      "enum": [
       "UNSPECIFIED",
       "DISMISS"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AffectedMembership": {
    "description": "Earlier we used to populate just the affected_members list and inferred the new membership state (roles didn't exist back then) from the Type. go/dynamite-finra required backend to know the previous membership state to reconstruct membership history. The proper solution involved cleaning up up Type enum, but it was used in many, many places. This was added as a stop-gap solution to unblock FINRA without breaking everything. Later role update and target audience update started[...]",
    "properties": {
     "affectedMember": {
      "$ref": "#/components/schemas/MemberId"
     },
     "priorMembershipRole": {
      "enum": [
       "ROLE_UNKNOWN",
       "ROLE_NONE",
       "ROLE_INVITEE",
       "ROLE_MEMBER",
       "ROLE_OWNER"
      ],
      "type": "string"
     },
     "priorMembershipState": {
      "enum": [
       "MEMBER_UNKNOWN",
       "MEMBER_INVITED",
       "MEMBER_JOINED",
       "MEMBER_NOT_A_MEMBER",
       "MEMBER_FAILED"
      ],
      "type": "string"
     },
     "targetMembershipRole": {
      "enum": [
       "ROLE_UNKNOWN",
       "ROLE_NONE",
       "ROLE_INVITEE",
       "ROLE_MEMBER",
       "ROLE_OWNER"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AllAuthenticatedUsersProto": {
    "description": "Represents a principal who has authenticated as any kind of user which the application understands. This is typically used for \"wiki-like\" security, where anyone is allowed access so long as they can be held accountable for that access. Since the purpose is knowing whom to blame, it is up to the application to decide what kinds of users it knows how to blame. For example, an application might choose to include GAIA users in \"all authenticated users\", but not include MDB u[...]",
    "type": "object"
   },
   "Annotation": {
    "description": "NOTE WHEN ADDING NEW PROTO FIELDS: Be sure to add datapol annotations to new fields with potential PII, so they get scrubbed when logging protos for errors. NEXT TAG: 31",
    "properties": {
     "babelPlaceholderMetadata": {
      "$ref": "#/components/schemas/BabelPlaceholderMetadata"
     },
     "cardCapabilityMetadata": {
      "$ref": "#/components/schemas/CardCapabilityMetadata"
     },
     "chipRenderType": {
      "description": "Whether the annotation should be rendered as a preview chip. If this is missing or unspecified, fallback to should_not_render on the metadata.",
      "enum": [
       "CHIP_RENDER_TYPE_UNSPECIFIED",
       "RENDER",
       "RENDER_IF_POSSIBLE",
       "DO_NOT_RENDER"
      ],
      "type": "string"
     },
     "consentedAppUnfurlMetadata": {
      "$ref": "#/components/schemas/ConsentedAppUnfurlMetadata"
     },
     "customEmojiMetadata": {
      "$ref": "#/components/schemas/CustomEmojiMetadata"
     },
     "dataLossPreventionMetadata": {
      "$ref": "#/components/schemas/DataLossPreventionMetadata"
     },
     "driveMetadata": {
      "$ref": "#/components/schemas/DriveMetadata"
     },
     "formatMetadata": {
      "$ref": "#/components/schemas/FormatMetadata"
     },
     "groupRetentionSettingsUpdated": {
      "$ref": "#/components/schemas/GroupRetentionSettingsUpdatedMetaData"
     },
     "gsuiteIntegrationMetadata": {
      "$ref": "#/components/schemas/GsuiteIntegrationMetadata"
     },
     "incomingWebhookChangedMetadata": {
      "$ref": "#/components/schemas/IncomingWebhookChangedMetadata"
     },
     "inlineRenderFormat": {
      "description": "The inline render format of this annotation. go/drive-smart-chips-chat-v2.",
      "enum": [
       "INLINE_RENDER_FORMAT_UNSPECIFIED",
       "SMART_CHIP"
      ],
      "type": "string"
     },
     "integrationConfigUpdated": {
      "$ref": "#/components/schemas/IntegrationConfigUpdatedMetadata"
     },
     "interactionData": {
      "$ref": "#/components/schemas/InteractionData"
     },
     "length": {
      "description": "Length of the text_body substring beginning from start_index the Annotation corresponds to.",
      "format": "int32",
      "type": "integer"
     },
     "localId": {
      "description": "* A client-assigned ID for this annotation. This is helpful in matching the back-filled annotations to the original annotations on client side, without having to re-parse the message. There is no guarantee an annotation has a local_id, it's a purely client used and controlled field with no guarantee of uniqueness.",
      "type": "string"
     },
     "membershipChanged": {
      "$ref": "#/components/schemas/MembershipChangedMetadata"
     },
     "readReceiptsSettingsMetadata": {
      "$ref": "#/components/schemas/ReadReceiptsSettingsUpdatedMetadata"
     },
     "requiredMessageFeaturesMetadata": {
      "$ref": "#/components/schemas/RequiredMessageFeaturesMetadata"
     },
     "roomUpdated": {
      "$ref": "#/components/schemas/RoomUpdatedMetadata"
     },
     "serverInvalidated": {
      "description": "Whether or not the annotation is invalidated by the server. Example of situations for invalidation include: when the URL is malformed, or when Drive item ID is rejected by Drive Service.",
      "type": "boolean"
     },
     "slashCommandMetadata": {
      "$ref": "#/components/schemas/SlashCommandMetadata"
     },
     "startIndex": {
      "description": "Start index (0-indexed) of the Message text the Annotation corresponds to, inclusive.",
      "format": "int32",
      "type": "integer"
     },
     "type": {
      "description": "Type of the Annotation.",
      "enum": [
       "TYPE_UNSPECIFIED",
       "URL",
       "DRIVE_FILE",
       "DRIVE_DOC",
       "DRIVE_SHEET",
       "DRIVE_SLIDE",
       "DRIVE_FORM",
       "USER_MENTION",
       "SLASH_COMMAND",
       "CONSENTED_APP_UNFURL",
       "VIDEO",
       "FORMAT_DATA",
       "IMAGE",
       "PDF",
       "VIDEO_CALL",
       "UPLOAD_METADATA",
       "GSUITE_INTEGRATION",
       "CUSTOM_EMOJI",
       "CARD_CAPABILITY",
       "DATA_LOSS_PREVENTION",
       "REQUIRED_MESSAGE_FEATURES_METADATA",
       "MEMBERSHIP_CHANGED",
       "ROOM_UPDATED",
       "GROUP_RETENTION_SETTINGS_UPDATED",
       "BABEL_PLACEHOLDER",
       "READ_RECEIPTS_SETTINGS_UPDATED",
       "INCOMING_WEBHOOK_CHANGED",
       "INTEGRATION_CONFIG_UPDATED",
       "INVITATION"
      ],
      "type": "string"
     },
     "uniqueId": {
      "description": "* A unique server-assigned ID for this annotation. This is helpful in matching annotation objects when fetched from service. All uploads should have a unique_id after the message they are attached to is successfully sent. Url annotations that originally were uploads (i.e. policy violations) will have a unique_id after the message they are attached to is successfully sent. No other url annotations should have a unique_id. All drive annotations should have a unique_id after t[...]",
      "type": "string"
     },
     "uploadMetadata": {
      "$ref": "#/components/schemas/UploadMetadata"
     },
     "urlMetadata": {
      "$ref": "#/components/schemas/UrlMetadata"
     },
     "userMentionMetadata": {
      "$ref": "#/components/schemas/UserMentionMetadata"
     },
     "videoCallMetadata": {
      "$ref": "#/components/schemas/VideoCallMetadata"
     },
     "youtubeMetadata": {
      "$ref": "#/components/schemas/YoutubeMetadata"
     }
    },
    "type": "object"
   },
   "AppId": {
    "description": "Identifier of an App.",
    "properties": {
     "appType": {
      "description": "Enum indicating the type of App this is.",
      "enum": [
       "APP_TYPE_UNSPECIFIED",
       "APP",
       "GSUITE_APP",
       "INCOMING_WEBHOOK"
      ],
      "type": "string"
     },
     "gsuiteAppType": {
      "description": "Enum indicating which 1P App this is when app_type is GSUITE_APP. Determined & set by the 1P API as a convenience for all users of this identifier(Eg. clients, chime, backend etc.) to map to 1P properties.",
      "enum": [
       "GSUITE_APP_TYPE_UNSPECIFIED",
       "TASKS_APP",
       "CALENDAR_APP",
       "DOCS_APP",
       "SHEETS_APP",
       "SLIDES_APP",
       "MEET_APP",
       "ASSISTIVE_SUGGESTION_APP",
       "CONTACTS_APP",
       "ACTIVITY_FEED_APP",
       "DRIVE_APP",
       "CHAT_IN_MEET_APP"
      ],
      "type": "string"
     },
     "id": {
      "description": "Numeric identifier of the App. Set to Project number for 1/3P Apps. For Webhook, this is WebhookId. Determined & set by the 1P API from App credentials on the side channel.",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedActivityFeedAnnotationData": {
    "description": "Next Id: 7",
    "properties": {
     "activityFeedMessageCreateTime": {
      "description": "Timestamp of when the Activity Feed message that contains this annotation was created. This is roughly when the activity happened, such as when a reaction happened, but will have at least some small delay, since the Activity Feed message is created asynchronously after. This timestamp should only be used for display when the activity create time is not available in the Chat UI, like the time of a reaction.",
      "format": "google-datetime",
      "type": "string"
     },
     "activityFeedMessageId": {
      "$ref": "#/components/schemas/MessageId"
     },
     "chatItem": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItem"
     },
     "sharedUserInfo": {
      "$ref": "#/components/schemas/UserInfo"
     },
     "userInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedActivityFeedAnnotationDataUserInfo"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedActivityFeedAnnotationDataUserInfo": {
    "description": "UserId of the AF item updater to show and the updater count to show.",
    "properties": {
     "updaterCountDisplayType": {
      "description": "Describes how updater_count_to_show should be used.",
      "enum": [
       "UPDATER_COUNT_DISPLAY_TYPE_UNSPECIFIED",
       "EXACT_COUNT",
       "NONZERO_COUNT"
      ],
      "type": "string"
     },
     "updaterCountToShow": {
      "description": "The number of updaters for clients to show, currently set to the total number of updaters minus the one set in updater_to_show.",
      "format": "int32",
      "type": "integer"
     },
     "updaterToShow": {
      "$ref": "#/components/schemas/UserId"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAppProfile": {
    "description": "Optional field for apps overriding display info",
    "properties": {
     "avatarEmoji": {
      "description": "Displayed user avatar emoji.",
      "type": "string"
     },
     "avatarUrl": {
      "description": "Displayed user avatar url.",
      "type": "string"
     },
     "name": {
      "description": "Displayed user name.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantAnnotationData": {
    "description": "This is the internal version of the API proto at google3/google/chat/v1/gsuite_message_integration.proto Data used to render Assistant suggestions. See go/bullseye-rendering.",
    "properties": {
     "suggestion": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAssistantSuggestion"
     },
     "unfulfillable": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAssistantUnfulfillableRequest"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantDebugContext": {
    "description": "Represents info regarding suggestion debug information.",
    "properties": {
     "query": {
      "description": "The query that triggered the resulting suggestion.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantFeedbackContext": {
    "description": "Data needed to render feedback on the Assistant card",
    "properties": {
     "feedbackChips": {
      "description": "Specifies a list of feedback chips to show",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteSharedAssistantFeedbackContextFeedbackChip"
      },
      "type": "array"
     },
     "thumbsFeedback": {
      "description": "Whether the thumbs feedback is provided",
      "enum": [
       "THUMBS_FEEDBACK_UNSPECIFIED",
       "NONE_SELECTED",
       "UP",
       "DOWN"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantFeedbackContextFeedbackChip": {
    "description": "Suggestion chips for users to indicate positive or negative feedback",
    "properties": {
     "feedbackChipType": {
      "description": "What type of chip to display",
      "enum": [
       "FEEDBACK_CHIP_TYPE_UNSPECIFIED",
       "WRONG_TRIGGER",
       "WRONG_FILE",
       "CORRECT_TRIGGER",
       "CORRECT_FILE",
       "DISRUPTIVE",
       "OTHER"
      ],
      "type": "string"
     },
     "state": {
      "description": "Whether the chip has been selected",
      "enum": [
       "FEEDBACK_CHIP_STATE_UNSPECIFIED",
       "SELECTED",
       "UNSELECTED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantSessionContext": {
    "description": "Session context specific for Assistant suggestions.",
    "properties": {
     "contextualSessionId": {
      "description": "Unique identifier populated by the contextual request handler for each vertical (Ex: File Suggestions, Smart Scheduling, etc.) that can be used to track sessions end-to-end. May span multiple users (sender-specific).",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantSuggestion": {
    "description": "Data for an Assistant suggestion.",
    "properties": {
     "debugContext": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAssistantDebugContext"
     },
     "feedbackContext": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAssistantFeedbackContext"
     },
     "findDocumentSuggestion": {
      "$ref": "#/components/schemas/AppsDynamiteSharedFindDocumentSuggestion"
     },
     "serializedSuggestions": {
      "description": "String representation of the suggestions provided.",
      "type": "string"
     },
     "sessionContext": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAssistantSessionContext"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedAssistantUnfulfillableRequest": {
    "description": "Data for a response to an unfulfillable request.",
    "type": "object"
   },
   "AppsDynamiteSharedAvatarInfo": {
    "properties": {
     "emoji": {
      "$ref": "#/components/schemas/AppsDynamiteSharedEmoji"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedBackendUploadMetadata": {
    "description": "Metadata used only in Dynamite backend for uploaded attachments.",
    "properties": {
     "blobPath": {
      "description": "Blobstore path for the uploaded attachment",
      "type": "string"
     },
     "contentName": {
      "description": "The original file name for the content, not the full path.",
      "type": "string"
     },
     "contentSize": {
      "description": "Scotty reported content size by default. http://google3/uploader/agent/scotty_agent.proto?l=101&rcl=140889785",
      "format": "int64",
      "type": "string"
     },
     "contentType": {
      "description": "Type is from Scotty's best_guess by default: http://google3/uploader/agent/scotty_agent.proto?l=51&rcl=140889785",
      "type": "string"
     },
     "dlpScanOutcome": {
      "description": "The results of the Data Loss Prevention (DLP) scan of the attachment. DEPRECATED: use dlp_scan_summary instead.",
      "enum": [
       "SCAN_UNKNOWN_OUTCOME",
       "SCAN_SUCCEEDED_NO_VIOLATION",
       "SCAN_SUCCEEDED_BLOCK",
       "SCAN_SUCCEEDED_WARN",
       "SCAN_SUCCEEDED_AUDIT_ONLY",
       "SCAN_FAILURE_EXCEPTION",
       "SCAN_FAILURE_RULE_FETCH_FAILED",
       "SCAN_FAILURE_TIMEOUT",
       "SCAN_FAILURE_ALL_RULES_FAILED",
       "SCAN_FAILURE_ILLEGAL_STATE_FOR_ATTACHMENTS",
       "SCAN_SKIPPED_EXPERIMENT_DISABLED",
       "SCAN_SKIPPED_CONSUMER",
       "SCAN_SKIPPED_NON_HUMAN_USER",
       "SCAN_SKIPPED_NO_MESSAGE",
       "SCAN_SKIPPED_USER_ACKNOWLEDGED_WARNING",
       "SCAN_SKIPPED_MESSAGE_FROM_UNSUPPORTED_ORIGIN",
       "SCAN_SKIPPED_MESSAGE_SENT_DURING_SPACE_MIGRATION",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_RULES_FOUND",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_APPLICABLE_RULES_FOR_ACTION_PARAMS",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_APPLICABLE_RULES_FOR_TRIGGER",
       "SCAN_RULE_EVALUATION_SKIPPED_CHANGELING_PERMANENT_ERROR",
       "SCAN_RULE_EVALUATION_SKIPPED_CHANGELING_EMPTY_RESPONSE",
       "SCAN_RULE_EVALUATION_SKIPPED_UNSUPPORTED_FILE_TYPE",
       "SCAN_SUCCEEDED_WITH_FAILURES_NO_VIOLATION",
       "SCAN_SUCCEEDED_WITH_FAILURES_BLOCK",
       "SCAN_SUCCEEDED_WITH_FAILURES_WARN",
       "SCAN_SUCCEEDED_WITH_FAILURES_AUDIT_ONLY"
      ],
      "type": "string"
     },
     "dlpScanSummary": {
      "$ref": "#/components/schemas/DlpScanSummary"
     },
     "groupId": {
      "$ref": "#/components/schemas/GroupId"
     },
     "isClientSideTranscodedVideo": {
      "description": "If the uploaded file is a video that has been transcoded on the client side Next tag: 18",
      "type": "boolean"
     },
     "originalDimension": {
      "$ref": "#/components/schemas/AppsDynamiteSharedDimension"
     },
     "quoteReplyMessageId": {
      "$ref": "#/components/schemas/MessageId"
     },
     "sha256": {
      "description": "The SHA256 hash of the attachment bytes.",
      "format": "byte",
      "type": "string"
     },
     "uploadIp": {
      "description": "User IP address at upload time. Ex. \"123.1.2.3\". Used by Ares abuse scanning.",
      "type": "string"
     },
     "uploadTimestampUsec": {
      "description": "Timestamp of when user finished uploading the content.",
      "format": "int64",
      "type": "string"
     },
     "videoId": {
      "description": "VideoID of the video attachments. This ID shall meets the Youtube ID format of 16 hex characters. For example, '4c14b8825af6059b' is a valid ID.",
      "type": "string"
     },
     "videoThumbnailBlobId": {
      "description": "Full Blobstore ID for the video thumbnail.",
      "type": "string"
     },
     "virusScanResult": {
      "description": "Result for a virus scan.",
      "enum": [
       "UNKNOWN_VIRUS_SCAN_RESULT",
       "CLEAN",
       "INFECTED",
       "ERROR",
       "POLICY_VIOLATION"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCalendarEventAnnotationData": {
    "properties": {
     "calendarEvent": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCalendarEventAnnotationDataCalendarEvent"
     },
     "eventCreation": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCalendarEventAnnotationDataEventCreation"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCalendarEventAnnotationDataCalendarEvent": {
    "properties": {
     "endTime": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCalendarEventAnnotationDataCalendarEventTime"
     },
     "eventId": {
      "description": "ID of the event.",
      "type": "string"
     },
     "startTime": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCalendarEventAnnotationDataCalendarEventTime"
     },
     "title": {
      "description": "Title of the event (at the time the message was generated).",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCalendarEventAnnotationDataCalendarEventTime": {
    "properties": {
     "allDay": {
      "$ref": "#/components/schemas/Date"
     },
     "timed": {
      "description": "Non all day event.",
      "format": "google-datetime",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCalendarEventAnnotationDataEventCreation": {
    "description": "Creation of an event (no extra data for now).",
    "type": "object"
   },
   "AppsDynamiteSharedCallAnnotationData": {
    "description": "Data used to render Meet or Google Voice chips in Chat. See go/dynamite-calling-artifacts-in-chat.",
    "properties": {
     "callEndedTimestamp": {
      "description": "Timestamp when the call ended. Used to render the call ended system message.",
      "format": "google-datetime",
      "type": "string"
     },
     "callMetadata": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCallMetadata"
     },
     "callStatus": {
      "description": "Required. Indicates the call status for the space. Used to determine the chip's state.",
      "enum": [
       "CALL_STATUS_UNSPECIFIED",
       "CALL_STARTED",
       "CALL_MISSED",
       "CALL_ENDED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCallMetadata": {
    "description": "Metadata required to generate call artifacts. This can either be the metadata for a Meet or, in the future, Google Voice call.",
    "properties": {
     "meetMetadata": {
      "$ref": "#/components/schemas/AppsDynamiteSharedMeetMetadata"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCardClickSuggestion": {
    "description": "Card click which identifies one suggestion provided by the app/bot.",
    "properties": {
     "actionId": {
      "description": "Identify the button/action that created the suggestion. A simple example would be a card button within the stream, or the id which can identify a specific suggestion.",
      "type": "string"
     },
     "suggestionMessageId": {
      "$ref": "#/components/schemas/MessageId"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItem": {
    "description": "Next Id: 5",
    "properties": {
     "activityInfo": {
      "description": "Information needed to render the specific type of feed item.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteSharedChatItemActivityInfo"
      },
      "type": "array"
     },
     "groupInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItemGroupInfo"
     },
     "messageInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedMessageInfo"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItemActivityInfo": {
    "properties": {
     "feedItemNudge": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItemActivityInfoFeedItemNudge"
     },
     "feedItemReactions": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItemActivityInfoFeedItemReactions"
     },
     "feedItemThreadReply": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItemActivityInfoFeedItemThreadReply"
     },
     "feedItemUserMention": {
      "$ref": "#/components/schemas/AppsDynamiteSharedChatItemActivityInfoFeedItemUserMention"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItemActivityInfoFeedItemNudge": {
    "description": "Existence of this attribute indicates that the AF item is for a message nudge item.",
    "properties": {
     "nudgeType": {
      "description": "Nudge type of the nudge feed item.",
      "enum": [
       "UNDEFINED",
       "REPLY",
       "FOLLOW_UP"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItemActivityInfoFeedItemReactions": {
    "description": "Existence of this attribute indicates that the AF item is for message reactions, but it is intentionally left empty since the list of reactions can be found in the top-level Message.Reactions.",
    "type": "object"
   },
   "AppsDynamiteSharedChatItemActivityInfoFeedItemThreadReply": {
    "description": "Existence of this attribute indicates that the AF item is for thread reply.",
    "properties": {
     "replyType": {
      "description": "Reply type of the thread reply feed item. The field is not persisted in storage. It's populated when constructing Activity Feed payload.",
      "enum": [
       "UNSPECIFIED",
       "ROOT",
       "FOLLOWER"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItemActivityInfoFeedItemUserMention": {
    "description": "Existence of this attribute indicates that the AF item is for a user mention item.",
    "properties": {
     "type": {
      "description": "User mention type",
      "enum": [
       "TYPE_UNSPECIFIED",
       "DIRECT",
       "ALL"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedChatItemGroupInfo": {
    "description": "Information about the space that the item originated from. This will be used to display Activity Feed items from rooms, and only contain the necessary information, such as the space name and group attributes. NEXT TAG: 6",
    "properties": {
     "attributeCheckerGroupType": {
      "description": "This is needed to determine what type of group the source message came from to support click-to-source.",
      "enum": [
       "ATTRIBUTE_CHECKER_GROUP_TYPE_UNSPECIFIED",
       "ONE_TO_ONE_HUMAN_DM",
       "ONE_TO_ONE_BOT_DM",
       "IMMUTABLE_MEMBERSHIP_GROUP_DM",
       "FLAT_ROOM",
       "THREADED_ROOM",
       "IMMUTABLE_MEMBERSHIP_HUMAN_DM",
       "POST_ROOM",
       "ACTIVITY_FEED"
      ],
      "type": "string"
     },
     "groupName": {
      "type": "string"
     },
     "groupReadTimeUsec": {
      "description": "Timestamp of when the group containing the message has been read by the user.",
      "format": "int64",
      "type": "string"
     },
     "inlineThreadingEnabled": {
      "description": "Indicates whether the group has inline replies enabled. If enabled, clients will render the space with inline replies.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedContentReportType": {
    "description": "Denotes a type of content report a user can send.",
    "properties": {
     "systemViolation": {
      "description": "Required. Google-defined system violation, covering the most common violations.",
      "enum": [
       "VIOLATION_UNSPECIFIED",
       "HARASSMENT",
       "DISCRIMINATION",
       "EXPLICIT_CONTENT",
       "SPAM",
       "CONFIDENTIAL_INFORMATION",
       "SENSITIVE_INFORMATION",
       "FRAUD",
       "MALWARE",
       "ILLEGAL_ACTIVITIES",
       "OTHER"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedCustomEmoji": {
    "description": "Proto representation of a custom emoji. May be used in both APIs and in Spanner, but certain fields should be restricted to one or the other. See the per-field documentation for details. NEXT_TAG: 14",
    "properties": {
     "blobId": {
      "description": "ID for the underlying image data in Blobstore. This field should *only* be present in Spanner or within the server, but should not be exposed in public APIs.",
      "type": "string"
     },
     "contentType": {
      "description": "Content type of the file used to upload the emoji. Used for takeout. Written to Spanner when the emoji is created.",
      "type": "string"
     },
     "createTimeMicros": {
      "description": "Time when the Emoji was created, in microseconds. This field may be present in Spanner, within the server, or in public APIs.",
      "format": "int64",
      "type": "string"
     },
     "creatorUserId": {
      "$ref": "#/components/schemas/UserId"
     },
     "deleteTimeMicros": {
      "description": "Time when the emoji was deleted, in microseconds. This field may be present in Spanner, within the server, or in public APIs. Only present if the emoji has been deleted.",
      "format": "int64",
      "type": "string"
     },
     "ephemeralUrl": {
      "description": "Output only. A short-lived URL clients can use for directly accessing a custom emoji image. This field is intended for API consumption, and should *never* be persisted to Spanner.",
      "readOnly": true,
      "type": "string"
     },
     "ownerCustomerId": {
      "$ref": "#/components/schemas/CustomerId"
     },
     "readToken": {
      "description": "Opaque token that clients use to construct the URL for accessing the custom emoji’s image data. This field is intended for API consumption, and should *never* be persisted to Spanner.",
      "type": "string"
     },
     "shortcode": {
      "description": "User-provided, human-readable ID for the custom emoji. Users are expected to observe this field in the UI instead of the UUID. This shortcode should be unique within an organization, but has no global uniqueness guarantees, unlike the UUID. This field should *never* be persisted to Spanner.",
      "type": "string"
     },
     "state": {
      "description": "Snapshot of the current state of the emoji, which may differ from the source-of-truth in the CustomEmojis table. This field should *never* be persisted to Spanner.",
      "enum": [
       "EMOJI_STATE_UNSPECIFIED",
       "EMOJI_ENABLED",
       "EMOJI_SYSTEM_DISABLED",
       "EMOJI_HIDDEN",
       "EMOJI_DELETED"
      ],
      "type": "string"
     },
     "updateTimeMicros": {
      "format": "int64",
      "type": "string"
     },
     "uuid": {
      "description": "Unique key for a custom emoji resource. Required. This field is *always* populated.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedDimension": {
    "description": "Dimension for the uploaded attachments.",
    "properties": {
     "height": {
      "format": "int32",
      "type": "integer"
     },
     "width": {
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedDlpMetricsMetadata": {
    "description": "LINT.IfChange",
    "properties": {
     "dlpStatus": {
      "description": "[required] Describes the DLP status of message send and attachment upload events.",
      "enum": [
       "DLP_STATUS_UNKNOWN",
       "DLP_DISABLED",
       "DLP_ENABLED_NO_RULE_FETCH",
       "DLP_ENABLED_RULES_FETCHED_NO_RULES",
       "DLP_ENABLED_RULES_FETCHED_NO_APPLICABLE_RULES",
       "DLP_ENABLED_RULES_FETCHED_AND_EVALUATED",
       "DLP_ENABLED_SCAN_TIMEOUT",
       "DLP_ENABLED_SCAN_FAILED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedDocument": {
    "description": "Data for rendering a document.",
    "properties": {
     "fileId": {
      "description": "Unique file ID.",
      "type": "string"
     },
     "justification": {
      "$ref": "#/components/schemas/AppsDynamiteSharedJustification"
     },
     "lastModifiedTime": {
      "description": "Time the document was last modified.",
      "format": "google-datetime",
      "type": "string"
     },
     "mimeType": {
      "description": "Used to determine which icon to render (e.g. docs, slides, sheets)",
      "type": "string"
     },
     "title": {
      "description": "Title of the document.",
      "type": "string"
     },
     "url": {
      "description": "URL of the document.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedEmoji": {
    "properties": {
     "customEmoji": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCustomEmoji"
     },
     "unicode": {
      "description": "A basic emoji represented by a unicode string.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedFindDocumentSuggestion": {
    "description": "Data for a FindDocument suggestion type.",
    "properties": {
     "documentSuggestions": {
      "description": "List of documents to render as suggestions.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteSharedDocument"
      },
      "type": "array"
     },
     "showActionButtons": {
      "description": "Whether to show the action buttons in the card for the suggestions.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedGroupDetails": {
    "description": "NEXT TAG: 3 A GroupDetails proto will store the information pertaining to single Group.",
    "properties": {
     "description": {
      "description": "A simple text that describes the purpose of a single Group, the general theme of the topics to be posted and/or the denominator of the Group participants.",
      "type": "string"
     },
     "guidelines": {
      "description": "A simple text describing the rules and expectations from members when participating in conversation.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedGroupVisibility": {
    "properties": {
     "state": {
      "enum": [
       "UNKNOWN",
       "PRIVATE",
       "PUBLIC"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedJustification": {
    "description": "Data for rendering a justification for a document.",
    "properties": {
     "actionTime": {
      "description": "Time the action took place.",
      "format": "google-datetime",
      "type": "string"
     },
     "actionType": {
      "description": "Type of action performed on the document.",
      "enum": [
       "ACTION_TYPE_UNSPECIFIED",
       "COMMENTED",
       "CREATED",
       "EDITED",
       "PRESENTED",
       "SHARED",
       "VIEWED",
       "COMMENT_RESOLVED",
       "SENT"
      ],
      "type": "string"
     },
     "documentOwner": {
      "$ref": "#/components/schemas/AppsDynamiteSharedJustificationPerson"
     },
     "topics": {
      "description": "Words or phrases from the user's query that describes the document content. (Ex: Users query is \"Can you share the document about Bullseye?\" the extracted topic would be \"Bullseye\").",
      "items": {
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedJustificationPerson": {
    "description": "Data for rendering a person associated with a document.",
    "properties": {
     "isRecipient": {
      "description": "Whether the person is the recipient of the suggestions.",
      "type": "boolean"
     },
     "user": {
      "$ref": "#/components/schemas/UserId"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedMeetMetadata": {
    "description": "Metadata specific for a Meet call that are required to generate call artifacts.",
    "properties": {
     "meetingCode": {
      "description": "Required. A globally unique code (e.g. \"cxv-zbgj-wzw\") that points to a meeting space. Note: Meeting codes may be regenerated, which will cause old meeting codes to become invalid.",
      "type": "string"
     },
     "meetingUrl": {
      "description": "Required. A URL, in the format \"https://meet.google.com/*\" (e.g. https://meet.google.com/cxv-zbgj-wzw), to identify and access the meeting space.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedMessageInfo": {
    "description": "Information that references a Dynamite chat message. This is only used for Activity Feed messages.",
    "properties": {
     "messageId": {
      "$ref": "#/components/schemas/MessageId"
     },
     "messageType": {
      "description": "The type of the source chat message.",
      "enum": [
       "MESSAGE_TYPE_UNSPECIFIED",
       "INLINE_REPLY"
      ],
      "type": "string"
     },
     "topicReadTimeUsec": {
      "description": "Timestamp of when the topic containing the message has been read by the user. This is populated if the message references an inline reply, in which case the space may be marked as read but the topic still has unread messages.",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedMessageIntegrationPayload": {
    "description": "The payload(restricted to 1P applications) to be stored with a specific message.",
    "properties": {
     "projectNumber": {
      "description": "Pantheon project number used to identify the calling app.",
      "format": "int64",
      "type": "string"
     },
     "tasksMessageIntegrationPayload": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksMessageIntegrationPayload"
     },
     "type": {
      "description": "An enum indicating which 1P application's payload this is. This field is required to add 1P payload.",
      "enum": [
       "PAYLOAD_TYPE_UNSPECIFIED",
       "TASKS"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedOrganizationInfo": {
    "description": "Contains info about the entity that something is, or is owned by.",
    "properties": {
     "consumerInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedOrganizationInfoConsumerInfo"
     },
     "customerInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedOrganizationInfoCustomerInfo"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedOrganizationInfoConsumerInfo": {
    "description": "Intentionally empty. Used to disambiguate consumer and customer use cases in oneof below.",
    "type": "object"
   },
   "AppsDynamiteSharedOrganizationInfoCustomerInfo": {
    "properties": {
     "customerId": {
      "$ref": "#/components/schemas/CustomerId"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedOriginAppSuggestion": {
    "description": "Stores the suggestion provided by apps/bots.",
    "properties": {
     "appId": {
      "$ref": "#/components/schemas/AppId"
     },
     "cardClickSuggestion": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCardClickSuggestion"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedPhoneNumber": {
    "properties": {
     "type": {
      "description": "The phone number type, e.g., work, mobile, etc.",
      "type": "string"
     },
     "value": {
      "description": "The actual phone number.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedReaction": {
    "properties": {
     "count": {
      "description": "The total number of users who have reacted.",
      "format": "int32",
      "type": "integer"
     },
     "createTimestamp": {
      "description": "When the first emoji of this type was added.",
      "format": "int64",
      "type": "string"
     },
     "currentUserParticipated": {
      "description": "Whether the current user reacted using this emoji. Note: Unlike most properties of messages, this is different per-user.",
      "type": "boolean"
     },
     "emoji": {
      "$ref": "#/components/schemas/AppsDynamiteSharedEmoji"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedRetentionSettings": {
    "description": "The settings of retention period of a message or topic.",
    "properties": {
     "expiryTimestamp": {
      "description": "The timestamp after which the message/topic should be removed, in microseconds since the epoch, when state == EPHEMERAL_ONE_DAY. The value should not be set in other cases.",
      "format": "int64",
      "type": "string"
     },
     "state": {
      "description": "The retention state.",
      "enum": [
       "UNKNOWN_RETENTION_STATE",
       "PERMANENT",
       "EPHEMERAL_ONE_DAY"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedSegmentedMembershipCount": {
    "description": "Contains info on membership count for member types: HUMAN_USER, APP_USER & ROSTER_MEMBER different states: INVITED, JOINED",
    "properties": {
     "memberType": {
      "enum": [
       "MEMBER_TYPE_UNSPECIFIED",
       "HUMAN_USER",
       "ROSTER_MEMBER"
      ],
      "type": "string"
     },
     "membershipCount": {
      "description": "count of members with given type and state",
      "format": "int32",
      "type": "integer"
     },
     "membershipState": {
      "enum": [
       "MEMBER_UNKNOWN",
       "MEMBER_INVITED",
       "MEMBER_JOINED",
       "MEMBER_NOT_A_MEMBER",
       "MEMBER_FAILED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedSegmentedMembershipCounts": {
    "properties": {
     "value": {
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteSharedSegmentedMembershipCount"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedSpaceInfo": {
    "description": "Defines the representation of a single matching space.",
    "properties": {
     "avatarInfo": {
      "$ref": "#/components/schemas/AppsDynamiteSharedAvatarInfo"
     },
     "avatarUrl": {
      "type": "string"
     },
     "description": {
      "type": "string"
     },
     "groupId": {
      "$ref": "#/components/schemas/GroupId"
     },
     "inviterEmail": {
      "description": "The email address of the user that invited the calling user to the room, if available. This field will only be populated for direct invites, it will be empty if the user was indirectly invited to the group.",
      "type": "string"
     },
     "isExternal": {
      "description": "Whether this is a space that enables guest access",
      "type": "boolean"
     },
     "name": {
      "type": "string"
     },
     "numMembers": {
      "description": "Deprecated. Use segmented_membership_counts instead which also includes other counts such as rosters.",
      "format": "int32",
      "type": "integer"
     },
     "segmentedMembershipCounts": {
      "$ref": "#/components/schemas/AppsDynamiteSharedSegmentedMembershipCounts"
     },
     "userMembershipState": {
      "description": "searching user's membership state in this space",
      "enum": [
       "MEMBER_UNKNOWN",
       "MEMBER_INVITED",
       "MEMBER_JOINED",
       "MEMBER_NOT_A_MEMBER",
       "MEMBER_FAILED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationData": {
    "description": "This is the internal version of the API proto at google3/google/chat/v1/gsuite_message_integration.proto",
    "properties": {
     "assigneeChange": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataAssigneeChange"
     },
     "completionChange": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataCompletionChange"
     },
     "creation": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataCreation"
     },
     "deletionChange": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataDeletionChange"
     },
     "taskId": {
      "description": "ID of task. Will be used to create deep links to Tasks.",
      "type": "string"
     },
     "taskProperties": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataTaskProperties"
     },
     "userDefinedMessage": {
      "$ref": "#/components/schemas/AppsDynamiteSharedTasksAnnotationDataUserDefinedMessage"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataAssigneeChange": {
    "properties": {
     "oldAssignee": {
      "$ref": "#/components/schemas/UserId"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataCompletionChange": {
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataCreation": {
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataDeletionChange": {
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataTaskProperties": {
    "description": "All relevant task properties for a Chat message.",
    "properties": {
     "assignee": {
      "$ref": "#/components/schemas/UserId"
     },
     "completed": {
      "description": "Whether the task is marked as completed.",
      "type": "boolean"
     },
     "deleted": {
      "description": "Whether the task is marked as deleted.",
      "type": "boolean"
     },
     "description": {
      "description": "The description of the task. If Task original description's length is greater than 1024, then Task BE sends the truncated description to Dynamite Integration Server.",
      "type": "string"
     },
     "startDate": {
      "$ref": "#/components/schemas/Date"
     },
     "startTime": {
      "description": "Set if the task has both a date and a time. Source of truth in Tasks BE: http://shortn/_u6cr0F5ttE",
      "format": "google-datetime",
      "type": "string"
     },
     "title": {
      "description": "The title of the task.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedTasksAnnotationDataUserDefinedMessage": {
    "description": "Used for task card attachments on custom user messages that should be kept as is without generating an i18n event message, e.g. the user starts a conversation from an existing task. IMPORTANT: please don't populate this field yet as it could break existing flows until it's implemented. See code at http://shortn/_CM74CdENMx used by http://shortn/_5o85POJY8Q.",
    "type": "object"
   },
   "AppsDynamiteSharedTasksMessageIntegrationPayload": {
    "description": "A payload containing Tasks metadata for rendering a live card. Currently not used by the Tasks integration.",
    "type": "object"
   },
   "AppsDynamiteSharedUserBlockRelationship": {
    "description": "User-block relationship",
    "properties": {
     "hasBlockedRequester": {
      "type": "boolean"
     },
     "isBlockedByRequester": {
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AppsDynamiteSharedVideoReference": {
    "description": "Reference to a transcoded video attachment.",
    "properties": {
     "format": {
      "description": "Available transcode format. Value is defined in video/storage/proto/content_header.proto",
      "items": {
       "format": "int32",
       "type": "integer"
      },
      "type": "array"
     },
     "status": {
      "description": "Transcode status",
      "enum": [
       "UNKNOWN_STATUS",
       "SUCCESS",
       "ERROR",
       "NOT_APPLICABLE",
       "THUMBNAIL_SUCCESS",
       "GO_LIVE_SUCCESS"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageAction": {
    "description": "An action that describes the behavior when the form is submitted. For example, an Apps Script can be invoked to handle the form.",
    "properties": {
     "function": {
      "description": "Apps Script function to invoke when the containing element is clicked/activated.",
      "type": "string"
     },
     "interaction": {
      "enum": [
       "INTERACTION_UNSPECIFIED",
       "OPEN_DIALOG"
      ],
      "type": "string"
     },
     "loadIndicator": {
      "enum": [
       "SPINNER",
       "NONE"
      ],
      "type": "string"
     },
     "persistValues": {
      "description": "Indicates whether form values persist after the action. The default value is `false`. If `true`, form values remain after the action is triggered. When using [LoadIndicator.NONE](workspace/add-ons/reference/rpc/google.apps.card.v1#loadindicator) for actions, `persist_values` = `true`is recommended, as it ensures that any changes made by the user after form or on change actions are sent to the server are not overwritten by the response. If `false`, the form values are cleare[...]",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageActionActionParameter": {
    "description": "List of string parameters to supply when the action method is invoked. For example, consider three snooze buttons: snooze now, snooze 1 day, snooze next week. You might use action method = snooze(), passing the snooze type and snooze time in the list of string parameters.",
    "properties": {
     "key": {
      "description": "The name of the parameter for the action script.",
      "type": "string"
     },
     "value": {
      "description": "The value of the parameter.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageBorderStyle": {
    "description": "Represents the complete border style applied to widgets.",
    "properties": {
     "cornerRadius": {
      "description": "The corner radius for the border.",
      "format": "int32",
      "type": "integer"
     },
     "strokeColor": {
      "$ref": "#/components/schemas/Color"
     },
     "type": {
      "description": "The border type.",
      "enum": [
       "BORDER_TYPE_UNSPECIFIED",
       "NO_BORDER",
       "STROKE"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageButton": {
    "description": "A button. Can be a text button or an image button.",
    "properties": {
     "altText": {
      "description": "The alternative text used for accessibility. Has no effect when an icon is set; use `icon.alt_text` instead.",
      "type": "string"
     },
     "color": {
      "$ref": "#/components/schemas/Color"
     },
     "disabled": {
      "description": "If true, the button is displayed in a disabled state and doesn't respond to user actions.",
      "type": "boolean"
     },
     "icon": {
      "$ref": "#/components/schemas/AppsDynamiteStorageIcon"
     },
     "onClick": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOnClick"
     },
     "text": {
      "description": "The text of the button.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageButtonList": {
    "description": "A list of buttons layed out horizontally.",
    "properties": {
     "buttons": {
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageButton"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageCard": {
    "description": "A card is a UI element that can contain UI widgets such as text and images. For more information, see Cards . For example, the following JSON creates a card that has a header with the name, position, icons, and link for a contact, followed by a section with contact information like email and phone number. ``` { \"header\": { \"title\": \"Heba Salam\", \"subtitle\": \"Software Engineer\", \"imageStyle\": \"ImageStyle.AVATAR\", \"imageUrl\": \"https://example.com/heba_salam.png[...]",
    "properties": {
     "cardActions": {
      "description": "The actions of this card. They are added to a card's generated toolbar menu. For example, the following JSON constructs a card action menu with Settings and Send Feedback options: ``` \"card_actions\": [ { \"actionLabel\": \"Setting\", \"onClick\": { \"action\": { \"functionName\": \"goToView\", \"parameters\": [ { \"key\": \"viewType\", \"value\": \"SETTING\" } ], \"loadIndicator\": \"LoadIndicator.SPINNER\" } } }, { \"actionLabel\": \"Send Feedback\", \"onClick\": { \"ope[...]",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageCardCardAction"
      },
      "type": "array"
     },
     "header": {
      "$ref": "#/components/schemas/AppsDynamiteStorageCardCardHeader"
     },
     "name": {
      "description": "Name of the card, which is used as a identifier for the card in card navigation.",
      "type": "string"
     },
     "sections": {
      "description": "Sections are separated by a line divider.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageCardSection"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageCardCardAction": {
    "description": "A card action is the action associated with the card. For example, an invoice card might include actions such as delete invoice, email invoice, or open the invoice in a browser.",
    "properties": {
     "actionLabel": {
      "description": "The label that displays as the action menu item.",
      "type": "string"
     },
     "onClick": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOnClick"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageCardCardHeader": {
    "properties": {
     "imageAltText": {
      "description": "The alternative text of this image which is used for accessibility.",
      "type": "string"
     },
     "imageType": {
      "description": "The image's type.",
      "enum": [
       "SQUARE",
       "CIRCLE"
      ],
      "type": "string"
     },
     "imageUrl": {
      "description": "The URL of the image in the card header.",
      "type": "string"
     },
     "subtitle": {
      "description": "The subtitle of the card header.",
      "type": "string"
     },
     "title": {
      "description": "The title of the card header. The title must be specified. The header has a fixed height: if both a title and subtitle are specified, each takes up one line. If only the title is specified, it takes up both lines.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageCardSection": {
    "description": "A section contains a collection of widgets that are rendered vertically in the order that they are specified. Across all platforms, cards have a narrow fixed width, so there is currently no need for layout properties, for example, float.",
    "properties": {
     "collapsible": {
      "description": "Indicates whether this section is collapsible. If a section is collapsible, the description must be given.",
      "type": "boolean"
     },
     "header": {
      "description": "The header of the section. Formatted text is supported.",
      "type": "string"
     },
     "uncollapsibleWidgetsCount": {
      "description": "The number of uncollapsible widgets. For example, when a section contains five widgets and the `numUncollapsibleWidget` is set to `2`, the first two widgets are always shown and the last three are collapsed as default. The `numUncollapsibleWidget` is taken into account only when collapsible is set to `true`.",
      "format": "int32",
      "type": "integer"
     },
     "widgets": {
      "description": "A section must contain at least 1 widget.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageWidget"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageColumns": {
    "description": "Represents a Columns widget that displays a single row of columns.",
    "properties": {
     "columnItems": {
      "description": "Each card supports up to 2 columns.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageColumnsColumn"
      },
      "type": "array"
     },
     "wrapStyle": {
      "description": "Controls how the column resizes based on screen width.",
      "enum": [
       "WRAP_STYLE_UNSPECIFIED",
       "NOWRAP",
       "WRAP"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageColumnsColumn": {
    "description": "Represents a Column that consists of widgets stacked vertically.",
    "properties": {
     "horizontalAlignment": {
      "description": "The horizontal alignment of the column.",
      "enum": [
       "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
       "START",
       "CENTER",
       "END"
      ],
      "type": "string"
     },
     "horizontalSizeStyle": {
      "description": "Specifies how the column content is sized horizontally.",
      "enum": [
       "HORIZONTAL_SIZE_STYLE_UNSPECIFIED",
       "FILL_AVAILABLE_SPACE",
       "FILL_MINIMUM_SPACE"
      ],
      "type": "string"
     },
     "verticalAlignment": {
      "description": "The vertical alignment of the column.",
      "enum": [
       "VERTICAL_ALIGNMENT_UNSPECIFIED",
       "CENTER",
       "TOP",
       "BOTTOM"
      ],
      "type": "string"
     },
     "widgets": {
      "description": "LINT.ThenChange(//depot/google3/google/apps/card/v1/card.proto) Array of widgets included in the column.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageColumnsColumnWidgets"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageColumnsColumnWidgets": {
    "description": "LINT.IfChange The `column` widget can contain these widgets.",
    "properties": {
     "buttonList": {
      "$ref": "#/components/schemas/AppsDynamiteStorageButtonList"
     },
     "dateTimePicker": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDateTimePicker"
     },
     "decoratedText": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDecoratedText"
     },
     "image": {
      "$ref": "#/components/schemas/AppsDynamiteStorageImage"
     },
     "selectionInput": {
      "$ref": "#/components/schemas/AppsDynamiteStorageSelectionInput"
     },
     "textInput": {
      "$ref": "#/components/schemas/AppsDynamiteStorageTextInput"
     },
     "textParagraph": {
      "$ref": "#/components/schemas/AppsDynamiteStorageTextParagraph"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageDateTimePicker": {
    "description": "The widget that lets users to specify a date and time.",
    "properties": {
     "label": {
      "description": "The label for the field that displays to the user.",
      "type": "string"
     },
     "name": {
      "description": "The name of the text input that's used in formInput, and uniquely identifies this input.",
      "type": "string"
     },
     "onChangeAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "timezoneOffsetDate": {
      "description": "The number representing the time zone offset from UTC, in minutes. If set, the `value_ms_epoch` is displayed in the specified time zone. If not set, it uses the user's time zone setting on the client side.",
      "format": "int32",
      "type": "integer"
     },
     "type": {
      "description": "The type of the date/time picker.",
      "enum": [
       "DATE_AND_TIME",
       "DATE_ONLY",
       "TIME_ONLY"
      ],
      "type": "string"
     },
     "valueMsEpoch": {
      "description": "The value to display as the default value before user input or previous user input. It is represented in milliseconds (Epoch time). For `DATE_AND_TIME` type, the full epoch value is used. For `DATE_ONLY` type, only date of the epoch time is used. For `TIME_ONLY` type, only time of the epoch time is used. For example, you can set epoch time to `3 * 60 * 60 * 1000` to represent 3am.",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageDecoratedText": {
    "description": "A widget that displays text with optional decorations such as a label above or below the text, an icon in front of the text, a selection widget or a button after the text.",
    "properties": {
     "bottomLabel": {
      "description": "The formatted text label that shows below the main text.",
      "type": "string"
     },
     "button": {
      "$ref": "#/components/schemas/AppsDynamiteStorageButton"
     },
     "endIcon": {
      "$ref": "#/components/schemas/AppsDynamiteStorageIcon"
     },
     "icon": {
      "$ref": "#/components/schemas/AppsDynamiteStorageIcon"
     },
     "onClick": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOnClick"
     },
     "startIcon": {
      "$ref": "#/components/schemas/AppsDynamiteStorageIcon"
     },
     "switchControl": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDecoratedTextSwitchControl"
     },
     "text": {
      "description": "Required. The main widget formatted text. See Text formatting for details.",
      "type": "string"
     },
     "topLabel": {
      "description": "The formatted text label that shows above the main text.",
      "type": "string"
     },
     "wrapText": {
      "description": "The wrap text setting. If `true`, the text is wrapped and displayed in multiline. Otherwise, the text is truncated.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageDecoratedTextSwitchControl": {
    "properties": {
     "controlType": {
      "description": "The control type, either switch or checkbox.",
      "enum": [
       "SWITCH",
       "CHECKBOX",
       "CHECK_BOX"
      ],
      "type": "string"
     },
     "name": {
      "description": "The name of the switch widget that's used in formInput.",
      "type": "string"
     },
     "onChangeAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "selected": {
      "description": "If the switch is selected.",
      "type": "boolean"
     },
     "value": {
      "description": "The value is what is passed back in the callback.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageDivider": {
    "description": "A divider that appears in between widgets.",
    "type": "object"
   },
   "AppsDynamiteStorageGrid": {
    "description": "Represents a Grid widget that displays items in a configurable grid layout.",
    "properties": {
     "borderStyle": {
      "$ref": "#/components/schemas/AppsDynamiteStorageBorderStyle"
     },
     "columnCount": {
      "description": "The number of columns to display in the grid. A default value is used if this field isn't specified, and that default value is different depending on where the grid is shown (dialog versus companion).",
      "format": "int32",
      "type": "integer"
     },
     "items": {
      "description": "The items to display in the grid.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageGridGridItem"
      },
      "type": "array"
     },
     "onClick": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOnClick"
     },
     "title": {
      "description": "The text that displays in the grid header.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageGridGridItem": {
    "description": "Represents a single item in the grid layout.",
    "properties": {
     "id": {
      "description": "A user-specified identifier for this grid item. This identifier is returned in the parent Grid's onClick callback parameters.",
      "type": "string"
     },
     "image": {
      "$ref": "#/components/schemas/AppsDynamiteStorageImageComponent"
     },
     "layout": {
      "description": "The layout to use for the grid item.",
      "enum": [
       "GRID_ITEM_LAYOUT_UNSPECIFIED",
       "TEXT_BELOW",
       "TEXT_ABOVE"
      ],
      "type": "string"
     },
     "subtitle": {
      "description": "The grid item's subtitle.",
      "type": "string"
     },
     "textAlignment": {
      "description": "The horizontal alignment of the grid item's text.",
      "enum": [
       "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
       "START",
       "CENTER",
       "END"
      ],
      "type": "string"
     },
     "title": {
      "description": "The grid item's title.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageIcon": {
    "properties": {
     "altText": {
      "description": "The description of the icon, used for accessibility. The default value is provided if you don't specify one.",
      "type": "string"
     },
     "iconUrl": {
      "description": "The icon specified by a URL.",
      "type": "string"
     },
     "imageType": {
      "description": "The crop style applied to the image. In some cases, applying a `CIRCLE` crop causes the image to be drawn larger than a standard icon.",
      "enum": [
       "SQUARE",
       "CIRCLE"
      ],
      "type": "string"
     },
     "knownIcon": {
      "description": "The icon specified by the string name of a list of known icons",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageImage": {
    "description": "An image that is specified by a URL and can have an onClick action.",
    "properties": {
     "altText": {
      "description": "The alternative text of this image, used for accessibility.",
      "type": "string"
     },
     "imageUrl": {
      "description": "An image URL.",
      "type": "string"
     },
     "onClick": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOnClick"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageImageComponent": {
    "properties": {
     "altText": {
      "description": "The accessibility label for the image.",
      "type": "string"
     },
     "borderStyle": {
      "$ref": "#/components/schemas/AppsDynamiteStorageBorderStyle"
     },
     "cropStyle": {
      "$ref": "#/components/schemas/AppsDynamiteStorageImageCropStyle"
     },
     "imageUri": {
      "description": "The image URL.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageImageCropStyle": {
    "description": "Represents the crop style applied to an image.",
    "properties": {
     "aspectRatio": {
      "description": "The aspect ratio to use if the crop type is `RECTANGLE_CUSTOM`.",
      "format": "double",
      "type": "number"
     },
     "type": {
      "description": "The crop type.",
      "enum": [
       "IMAGE_CROP_TYPE_UNSPECIFIED",
       "SQUARE",
       "CIRCLE",
       "RECTANGLE_CUSTOM",
       "RECTANGLE_4_3"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageOnClick": {
    "properties": {
     "action": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "hostAppAction": {
      "$ref": "#/components/schemas/HostAppActionMarkup"
     },
     "openDynamicLinkAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "openLink": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOpenLink"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageOpenLink": {
    "properties": {
     "appUri": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOpenLinkAppUri"
     },
     "onClose": {
      "enum": [
       "NOTHING",
       "RELOAD"
      ],
      "type": "string"
     },
     "openAs": {
      "enum": [
       "FULL_SIZE",
       "OVERLAY"
      ],
      "type": "string"
     },
     "url": {
      "description": "The URL to open.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageOpenLinkAppUri": {
    "description": "Represents the platform specific uri/intent to open for each client.",
    "properties": {
     "androidIntent": {
      "$ref": "#/components/schemas/AppsDynamiteStorageOpenLinkAppUriIntent"
     },
     "companionUri": {
      "description": "A companion uri string to be opened in the chat companion window. on the web.",
      "type": "string"
     },
     "iosUri": {
      "description": "A uri string to be opened in the corresponding iOS hosting app.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageOpenLinkAppUriIntent": {
    "description": "Android intent.",
    "properties": {
     "extraData": {
      "description": "A list of extra data for the android intent. For example, for a calendar event edit intent, the event title information can be passed as extra data.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageOpenLinkAppUriIntentExtraData"
      },
      "type": "array"
     },
     "intentAction": {
      "description": "An android intent action string for the {@link android.content.Intent} object. For example: for the view intent action type, a valid value will be android.content.Intent.ACTION_VIEW.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageOpenLinkAppUriIntentExtraData": {
    "description": "Extra data for an android intent. Valid keys are defined in the hosting app contract.",
    "properties": {
     "key": {
      "description": "A key for the intent extra data.",
      "type": "string"
     },
     "value": {
      "description": "Value for the given extra data key.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageSelectionInput": {
    "description": "A widget that creates a UI item (for example, a drop-down list) with options for users to select.",
    "properties": {
     "items": {
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageSelectionInputSelectionItem"
      },
      "type": "array"
     },
     "label": {
      "description": "The label displayed ahead of the switch control.",
      "type": "string"
     },
     "name": {
      "description": "The name of the text input which is used in formInput.",
      "type": "string"
     },
     "onChangeAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "type": {
      "enum": [
       "CHECK_BOX",
       "RADIO_BUTTON",
       "SWITCH",
       "DROPDOWN",
       "MULTI_SELECT"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageSelectionInputSelectionItem": {
    "description": "The item in the switch control. A radio button, at most one of the items is selected.",
    "properties": {
     "selected": {
      "description": "If more than one item is selected for `RADIO_BUTTON` and `DROPDOWN`, the first selected item is treated as selected and the ones after are ignored.",
      "type": "boolean"
     },
     "text": {
      "description": "The text to be displayed.",
      "type": "string"
     },
     "value": {
      "description": "The value associated with this item. The client should use this as a form input value.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageSuggestions": {
    "description": "A container wrapping elements necessary for showing suggestion items used in text input autocomplete.",
    "properties": {
     "items": {
      "description": "A list of suggestions items which will be used in are used in autocomplete.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteStorageSuggestionsSuggestionItem"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageSuggestionsSuggestionItem": {
    "description": "A suggestion item. Only supports text for now.",
    "properties": {
     "text": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageTextInput": {
    "description": "A text input is a UI item where users can input text. A text input can also have an onChange action and suggestions.",
    "properties": {
     "autoCompleteAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "hintText": {
      "description": "The hint text.",
      "type": "string"
     },
     "initialSuggestions": {
      "$ref": "#/components/schemas/AppsDynamiteStorageSuggestions"
     },
     "label": {
      "description": "At least one of label and hintText must be specified.",
      "type": "string"
     },
     "name": {
      "description": "The name of the text input which is used in formInput.",
      "type": "string"
     },
     "onChangeAction": {
      "$ref": "#/components/schemas/AppsDynamiteStorageAction"
     },
     "type": {
      "description": "The style of the text, for example, a single line or multiple lines.",
      "enum": [
       "SINGLE_LINE",
       "MULTIPLE_LINE"
      ],
      "type": "string"
     },
     "value": {
      "description": "The default value when there is no input from the user.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageTextParagraph": {
    "description": "A paragraph of text that supports formatting. See [Text formatting](workspace/add-ons/concepts/widgets#text_formatting\") for details.",
    "properties": {
     "text": {
      "description": "The text that's shown in the widget.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteStorageWidget": {
    "description": "A widget is a UI element that presents texts, images, etc.",
    "properties": {
     "buttonList": {
      "$ref": "#/components/schemas/AppsDynamiteStorageButtonList"
     },
     "columns": {
      "$ref": "#/components/schemas/AppsDynamiteStorageColumns"
     },
     "dateTimePicker": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDateTimePicker"
     },
     "decoratedText": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDecoratedText"
     },
     "divider": {
      "$ref": "#/components/schemas/AppsDynamiteStorageDivider"
     },
     "grid": {
      "$ref": "#/components/schemas/AppsDynamiteStorageGrid"
     },
     "horizontalAlignment": {
      "description": "The horizontal alignment of this widget.",
      "enum": [
       "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
       "START",
       "CENTER",
       "END"
      ],
      "type": "string"
     },
     "image": {
      "$ref": "#/components/schemas/AppsDynamiteStorageImage"
     },
     "selectionInput": {
      "$ref": "#/components/schemas/AppsDynamiteStorageSelectionInput"
     },
     "textInput": {
      "$ref": "#/components/schemas/AppsDynamiteStorageTextInput"
     },
     "textParagraph": {
      "$ref": "#/components/schemas/AppsDynamiteStorageTextParagraph"
     }
    },
    "type": "object"
   },
   "AppsDynamiteV1ApiCompatV1Action": {
    "description": "Interactive objects inside a message. Documentation: - https://api.slack.com/docs/message-buttons",
    "properties": {
     "confirm": {
      "$ref": "#/components/schemas/AppsDynamiteV1ApiCompatV1ActionConfirm"
     },
     "name": {
      "description": "Unique identifier for this action.",
      "type": "string"
     },
     "style": {
      "description": "Button style (\"default\", \"primary\", or \"danger\").",
      "type": "string"
     },
     "text": {
      "description": "User-facing label for the action.",
      "type": "string"
     },
     "type": {
      "description": "Action type - currently only \"button\".",
      "type": "string"
     },
     "value": {
      "description": "Payload for this action. Will be sent to the action handler along with name.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteV1ApiCompatV1ActionConfirm": {
    "description": "Confirmation dialog config.",
    "properties": {
     "dismiss_text": {
      "description": "\"Cancel\" button label.",
      "type": "string"
     },
     "ok_text": {
      "description": "\"OK\" button label.",
      "type": "string"
     },
     "text": {
      "description": "Confirmation dialog body text.",
      "type": "string"
     },
     "title": {
      "description": "Confirmation dialog title.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsDynamiteV1ApiCompatV1Attachment": {
    "description": "Richly formatted attachments. Documentation: - https://api.slack.com/docs/message-attachments",
    "properties": {
     "actions": {
      "description": "Array of actions (currently only buttons).",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteV1ApiCompatV1Action"
      },
      "type": "array"
     },
     "attachment_type": {
      "description": "Undocumented - used in interactive button examples. The only valid value appears to be \"default\".",
      "type": "string"
     },
     "author_icon": {
      "description": "Avatar URL for the user.",
      "type": "string"
     },
     "author_link": {
      "description": "URL that the user name should link to.",
      "type": "string"
     },
     "author_name": {
      "description": "User name to display as the author of the message.",
      "type": "string"
     },
     "callback_id": {
      "description": "Unique identifier for the collection of buttons within this attachment. Will be sent back to the action handler URL when a button is clicked.",
      "type": "string"
     },
     "color": {
      "description": "A color \"bar\" to display to the left of the attachment.",
      "type": "string"
     },
     "fallback": {
      "description": "Fallback plain-text string for clients that don't support attachments.",
      "type": "string"
     },
     "fields": {
      "description": "Columns of text inside the attachment body.",
      "items": {
       "$ref": "#/components/schemas/AppsDynamiteV1ApiCompatV1Field"
      },
      "type": "array"
     },
     "footer": {
      "description": "A string displayed at the bottom of the attachment.",
      "type": "string"
     },
     "footer_icon": {
      "description": "Avatar URL displayed to the left of the footer.",
      "type": "string"
     },
     "image_url": {
      "description": "URL of an image to display in an image chip.",
      "type": "string"
     },
     "mrkdwn_in": {
      "description": "List of fields to apply formatting to.",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "pretext": {
      "description": "A string to show above the attachment.",
      "type": "string"
     },
     "text": {
      "description": "Main text.",
      "type": "string"
     },
     "thumb_url": {
      "description": "URL of a thumbnail image to display to the right of the attachment body.",
      "type": "string"
     },
     "title": {
      "description": "Title string of this attachment.",
      "type": "string"
     },
     "title_link": {
      "description": "URL that the title string should link to.",
      "type": "string"
     },
     "ts": {
      "description": "UNIX timestamp of the attachment.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "AppsDynamiteV1ApiCompatV1Field": {
    "description": "A column of text in an attachment. Documentation: - https://api.slack.com/docs/message-attachments",
    "properties": {
     "short": {
      "description": "Whether the field can be shown side-by-side with another field.",
      "type": "boolean"
     },
     "title": {
      "description": "The heading text, shown in bold.",
      "type": "string"
     },
     "value": {
      "description": "The text value of the field.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkup": {
    "properties": {
     "addonAttachments": {
      "items": {
       "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkupAddonAttachment"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkupAddonAttachment": {
    "properties": {
     "iconUrl": {
      "description": "Link to the resource's icon.",
      "type": "string"
     },
     "mimeType": {
      "description": "MIME type of the content in resource_url.",
      "type": "string"
     },
     "resourceUrl": {
      "type": "string"
     },
     "title": {
      "description": "Title of the attachment.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkup": {
    "description": "Markup that defines conference data associated to a Google Calendar event.",
    "properties": {
     "conferenceId": {
      "description": "Unique identifier for this conference data. Maximum 512 characters long.",
      "type": "string"
     },
     "conferenceSolutionId": {
      "description": "An identifier of the conferencing solution. Must match a value from the deployment's `calendar.conferenceSolution.id` field.",
      "type": "string"
     },
     "entryPoints": {
      "description": "Entry points to the conference. Maximum 300 entry points are allowed.",
      "items": {
       "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupEntryPointMarkup"
      },
      "type": "array"
     },
     "error": {
      "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupError"
     },
     "note": {
      "description": "Additional notes (such as instructions from the administrator, legal notices) to display to the user. Can contain HTML. Max length 2048 characters.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupEntryPointMarkup": {
    "description": "A way to join the conference.",
    "properties": {
     "accessCode": {
      "description": "An access code for accessing the conference. Maximum 128 characters long.",
      "type": "string"
     },
     "features": {
      "description": "Features of the entry point, such as being toll or toll-free. One entry point can have multiple features.",
      "items": {
       "enum": [
        "UNKNOWN_FEATURE",
        "TOLL",
        "TOLL_FREE"
       ],
       "type": "string"
      },
      "type": "array"
     },
     "label": {
      "description": "The label of the entry point to display to the user. Maximum 512 characters long.",
      "type": "string"
     },
     "meetingCode": {
      "description": "A meeting code for accessing the conference. Maximum 128 characters long.",
      "type": "string"
     },
     "passcode": {
      "description": "A passcode for accessing the conference. Maximum 128 characters long.",
      "type": "string"
     },
     "password": {
      "description": "A password for accessing the conference. Maximum 128 characters long.",
      "type": "string"
     },
     "pin": {
      "description": "A PIN for accessing the conference. Maximum 128 characters long.",
      "type": "string"
     },
     "regionCode": {
      "description": "The CLDR/ISO 3166 region code for the country associated with this entry point. Applicable only to `Type.PHONE`.",
      "type": "string"
     },
     "type": {
      "description": "The type of the entry point. Required.",
      "enum": [
       "UNKNOWN",
       "VIDEO",
       "PHONE",
       "MORE",
       "SIP"
      ],
      "type": "string"
     },
     "uri": {
      "description": "A URI for joining the conference. Supports tel: and http(s): and should be at most 1300 characters long. Required.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupError": {
    "description": "Represents an error that occurred during conference creation.",
    "properties": {
     "authenticationUrl": {
      "description": "If the error type is `AUTHENTICATION`, the add-on can provide a URL allowing users to log in. Maximum 1300 characters long.",
      "type": "string"
     },
     "type": {
      "description": "The type of error. Required.",
      "enum": [
       "UNKNOWN",
       "AUTHENTICATION",
       "TEMPORARY",
       "PERMANENT",
       "PERMISSION_DENIED",
       "CONFERENCE_SOLUTION_FORBIDDEN"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkupParameter": {
    "description": "Solution-specific parameters that are persisted with the event data and, if an update or delete is needed, are passed to the add-on. For example: `[{key: 'sessionKey', value: '123'}, {key: 'meetingId', value: '456'}]`",
    "properties": {
     "key": {
      "description": "The key of the parameter. Maximum 50 characters long. Required.",
      "type": "string"
     },
     "value": {
      "description": "The value of the parameter. Maximum 1024 characters long. Required.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupEditAttendeesActionMarkup": {
    "properties": {
     "addAttendeeEmails": {
      "description": "A list of attendees to add to the Google Calendar event.",
      "items": {
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AppsExtensionsMarkupCalendarClientActionMarkupEditConferenceDataActionMarkup": {
    "properties": {
     "conferenceData": {
      "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupConferenceDataMarkup"
     }
    },
    "type": "object"
   },
   "Attachment": {
    "description": "Attachments that follow the message text.",
    "properties": {
     "addOnData": {
      "$ref": "#/components/schemas/GoogleChatV1ContextualAddOnMarkup"
     },
     "appId": {
      "$ref": "#/components/schemas/UserId"
     },
     "attachmentId": {
      "description": "To identify an attachment within repeated in a message",
      "type": "string"
     },
     "cardAddOnData": {
      "$ref": "#/components/schemas/AppsDynamiteStorageCard"
     },
     "deprecatedAddOnData": {
      "$ref": "#/components/schemas/ContextualAddOnMarkup"
     },
     "slackData": {
      "$ref": "#/components/schemas/AppsDynamiteV1ApiCompatV1Attachment"
     },
     "slackDataImageUrlHeight": {
      "description": "The height of image url as fetched by fife. This field is asynchronously filled.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "Attribute": {
    "description": "An Attribute is a piece of data attached an Item. Attributes are opaque to the Starbox and have no effect on, nor are they effected by, message storage, indexing, or search. ",
    "properties": {
     "name": {
      "description": "The name of the attribute. Required - If a write is attempted with an empty string, the server will return an error.",
      "type": "string"
     },
     "value": {
      "$ref": "#/components/schemas/CaribouAttributeValue"
     }
    },
    "type": "object"
   },
   "AttributeRemoved": {
    "description": "An attribute was deleted from some (subset of the) messages in this thread.",
    "properties": {
     "attributeId": {
      "type": "string"
     },
     "messageKeys": {
      "items": {
       "$ref": "#/components/schemas/MultiKey"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AttributeSet": {
    "description": "An attribute was added to some (subset of the) messages in this thread.",
    "properties": {
     "attributeId": {
      "type": "string"
     },
     "attributeValue": {
      "description": "The serialized attribute_value as persisted in the storage layer. The application is responsible for deserializing it to an Attribute.Value if appropriate.",
      "format": "byte",
      "type": "string"
     },
     "messageKeys": {
      "items": {
       "$ref": "#/components/schemas/MultiKey"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "Attributes": {
    "properties": {
     "attribute": {
      "items": {
       "$ref": "#/components/schemas/Attribute"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AuditLoggingSettings": {
    "description": "Represents the settings for Cloud audit logging",
    "properties": {
     "logAdminReadActions": {
      "description": "Indicates whether audit logging is on/off for admin activity read APIs i.e. Get/List DataSources, Get/List SearchApplications etc.",
      "type": "boolean"
     },
     "logDataReadActions": {
      "description": "Indicates whether audit logging is on/off for data access read APIs i.e. ListItems, GetItem etc.",
      "type": "boolean"
     },
     "logDataWriteActions": {
      "description": "Indicates whether audit logging is on/off for data access write APIs i.e. IndexItem etc.",
      "type": "boolean"
     },
     "project": {
      "description": "The resource name of the GCP Project to store audit logs. Cloud audit logging will be enabled after project_name has been updated through CustomerService. Format: projects/{project_id}",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AuthorizedItemId": {
    "description": "A combination of an identifier for a Drive resource (e.g. file, folder, or drive) and any secrets needed to access it. The secrets should never be logged, and this proto annotates those secret fields to ensure that they are not. Clients are encouraged to use this proto rather than defining their own, to ensure that secrets are correctly annotated.",
    "properties": {
     "id": {
      "description": "Serialized ID of the Drive resource",
      "type": "string"
     },
     "resourceKey": {
      "description": "Resource key of the Drive item. This field should be unset if, depending on the context, the item does not have a resource key, or if none was specified. This must never be logged.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "AutoComplete": {
    "properties": {
     "items": {
      "items": {
       "$ref": "#/components/schemas/AutoCompleteItem"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "AutoCompleteItem": {
    "properties": {
     "text": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "BabelMessageProps": {
    "description": "Container for Babel (Hangouts Classic) only message properties. The properties here will not be consumed by Dynamite clients. They are relevant only for Hangouts Classic.",
    "properties": {
     "clientGeneratedId": {
      "description": "Babel clients locally generate this ID to dedupe against the async fanout.",
      "format": "int64",
      "type": "string"
     },
     "contentExtension": {
      "$ref": "#/components/schemas/ChatContentExtension"
     },
     "deliveryMedium": {
      "$ref": "#/components/schemas/DeliveryMedium"
     },
     "eventId": {
      "description": "Primary identifier used by Hangouts Classic for its events (messages).",
      "type": "string"
     },
     "messageContent": {
      "$ref": "#/components/schemas/ChatConserverMessageContent"
     },
     "wasUpdatedByBackfill": {
      "description": "Whether or not these message properties were backfilled by go/dinnertrain.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "BabelPlaceholderMetadata": {
    "description": "Annotation metadata for Babel-only items that signals which type of placeholder message should be displayed in Babel clients.",
    "properties": {
     "deleteMetadata": {
      "$ref": "#/components/schemas/DeleteMetadata"
     },
     "editMetadata": {
      "$ref": "#/components/schemas/EditMetadata"
     },
     "hangoutVideoMetadata": {
      "$ref": "#/components/schemas/HangoutVideoEventMetadata"
     }
    },
    "type": "object"
   },
   "BooleanOperatorOptions": {
    "description": "Used to provide a search operator for boolean properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
    "properties": {
     "operatorName": {
      "description": "Indicates the operator name required in the query in order to isolate the boolean property. For example, if operatorName is *closed* and the property's name is *isClosed*, then queries like *closed:<value>* show results only where the value of the property named *isClosed* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any String properties or text within the content field for [...]",
      "type": "string"
     }
    },
    "type": "object"
   },
   "BooleanPropertyOptions": {
    "description": "The options for boolean properties.",
    "properties": {
     "operatorOptions": {
      "$ref": "#/components/schemas/BooleanOperatorOptions"
     }
    },
    "type": "object"
   },
   "BorderStyle": {
    "description": "Represents a complete border style that can be applied to widgets.",
    "properties": {
     "cornerRadius": {
      "description": "The corner radius for the border.",
      "format": "int32",
      "type": "integer"
     },
     "strokeColor": {
      "description": "The colors to use when the type is STROKE.",
      "type": "string"
     },
     "type": {
      "description": "The border type.",
      "enum": [
       "BORDER_TYPE_NOT_SET",
       "NO_BORDER",
       "STROKE"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "BotInfo": {
    "description": "Bot-specific profile information.",
    "properties": {
     "appAllowlistStatus": {
      "enum": [
       "UNSPECIFIED_STATUS",
       "ALLOWED",
       "ALL_APPS_DISABLED_BY_ADMIN",
       "APP_NOT_ALLOWLISTED_BY_ADMIN"
      ],
      "type": "string"
     },
     "appId": {
      "$ref": "#/components/schemas/AppId"
     },
     "botAvatarUrl": {
      "description": "URL for the avatar picture of the User in dynamite. This field should be populated if the request is FetchBotCategories/ListBotCatalogEntries",
      "type": "string"
     },
     "botName": {
      "description": "Non-unique, user-defined display name of the Bot. This field should be populated if the request is FetchBotCategories/ListBotCatalogEntries.",
      "type": "string"
     },
     "description": {
      "description": "Short description for the bot.",
      "type": "string"
     },
     "developerName": {
      "description": "Name of bot developer.",
      "type": "string"
     },
     "marketPlaceBannerUrl": {
      "description": "URL for the banner image in GSuite Market Place. The banner will be 220x140.",
      "type": "string"
     },
     "status": {
      "description": "Indicates whether bot is enabled/disabled.",
      "enum": [
       "UNKNOWN_STATUS",
       "ENABLED",
       "DISABLED_BY_DEVELOPER"
      ],
      "type": "string"
     },
     "supportHomeScreen": {
      "description": "If the app supports a home screen.",
      "type": "boolean"
     },
     "supportUrls": {
      "$ref": "#/components/schemas/SupportUrls"
     },
     "supportedUses": {
      "description": "The supported uses are limited according to the user that made the request. If the user does not have permission to use the bot, the list will be empty. This could occur for non whitelisted bots in the catalog.",
      "items": {
       "enum": [
        "UNKNOWN",
        "CAN_ADD_TO_DM",
        "CAN_ADD_TO_ROOM",
        "CAN_ADD_TO_HUMAN_DM"
       ],
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "BotResponse": {
    "description": "Information about a bot response, branched from shared/bot_response.proto without frontend User proto as we never store it.",
    "properties": {
     "botId": {
      "$ref": "#/components/schemas/UserId"
     },
     "requiredAction": {
      "enum": [
       "UNKNOWN_SETUP_TYPE",
       "CONFIGURATION",
       "AUTHENTICATION"
      ],
      "type": "string"
     },
     "responseType": {
      "enum": [
       "UNKNOWN_RESPONSE_TYPE",
       "ERROR",
       "SETUP_REQUIRED",
       "DISABLED_BY_ADMIN",
       "DISABLED_BY_DEVELOPER",
       "PRIVATE",
       "APP_SUGGESTION"
      ],
      "type": "string"
     },
     "setupUrl": {
      "description": "URL for setting up bot.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "BroadcastAccess": {
    "description": "Broadcast access information of a meeting space.",
    "properties": {
     "accessPolicy": {
      "description": "The policy that controls the broadcast's viewer access.",
      "enum": [
       "BROADCASTING_ACCESS_POLICY_UNSPECIFIED",
       "ORGANIZATION",
       "PUBLIC"
      ],
      "type": "string"
     },
     "viewUrl": {
      "description": "A URL that can be used to access the broadcast of the meeting. This field will be empty if broadcast is not enabled. It will be populated by the backend. Clients cannot modify the value.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "BroadcastSessionInfo": {
    "description": "Information about a broadcast session.",
    "properties": {
     "broadcastSessionId": {
      "description": "A unique server-generated ID for the broadcast session.",
      "type": "string"
     },
     "broadcastStats": {
      "$ref": "#/components/schemas/BroadcastStats"
     },
     "ingestionId": {
      "description": "Input only. Deprecated field, should not be used.",
      "type": "string"
     },
     "sessionStateInfo": {
      "$ref": "#/components/schemas/SessionStateInfo"
     }
    },
    "type": "object"
   },
   "BroadcastStats": {
    "description": "Statistics of the broadcast session.",
    "properties": {
     "estimatedViewerCount": {
      "description": "Estimated concurrent viewer count.",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "Button": {
    "properties": {
     "imageButton": {
      "$ref": "#/components/schemas/ImageButton"
     },
     "textButton": {
      "$ref": "#/components/schemas/TextButton"
     }
    },
    "type": "object"
   },
   "CalendarClientActionMarkup": {
    "properties": {
     "addAttachmentsActionMarkup": {
      "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupAddAttachmentsActionMarkup"
     },
     "editAttendeesActionMarkup": {
      "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupEditAttendeesActionMarkup"
     },
     "editConferenceDataActionMarkup": {
      "$ref": "#/components/schemas/AppsExtensionsMarkupCalendarClientActionMarkupEditConferenceDataActionMarkup"
     }
    },
    "type": "object"
   },
   "CallInfo": {
    "description": "Contains information regarding an ongoing conference (aka call) for a meeting space.",
    "properties": {
     "abuseReportingConfig": {
      "$ref": "#/components/schemas/AbuseReportingConfig"
     },
     "artifactOwner": {
      "$ref": "#/components/schemas/UserDisplayInfo"
     },
     "attachedDocuments": {
      "description": "Output only. Documents attached to an ongoing conference.",
      "items": {
       "$ref": "#/components/schemas/DocumentInfo"
      },
      "readOnly": true,
      "type": "array"
     },
     "availableAccessTypes": {
      "description": "List of available access types of the conference.",
      "items": {
       "enum": [
        "ACCESS_TYPE_UNSPECIFIED",
        "ACCESS_TYPE_OPEN",
        "ACCESS_TYPE_TRUSTED",
        "ACCESS_TYPE_RESTRICTED",
        "ACCESS_TYPE_CLOSED"
       ],
       "type": "string"
      },
      "type": "array"
     },
     "availableReactions": {
      "description": "Output only. The set of reactions that clients are allowed to send and can expect to receive. Note that a device in the conference should have the MAY_SEND_REACTIONS privilege to be able to send reactions.",
      "items": {
       "$ref": "#/components/schemas/ReactionInfo"
      },
      "readOnly": true,
      "type": "array"
     },
     "broadcastSessionInfo": {
      "$ref": "#/components/schemas/BroadcastSessionInfo"
     },
     "calendarEventId": {
      "description": "Output only. The calendar event ID of a Google Calendar event that the meeting space is associated with. If the meeting space is not associated with an event in Google Calendar, this field is empty. For recurring events, it refers to the recurring instance associated with the current call, as determined by the server.",
      "readOnly": true,
      "type": "string"
     },
     "coActivity": {
      "$ref": "#/components/schemas/CoActivity"
     },
     "collaboration": {
      "$ref": "#/components/schemas/Collaboration"
     },
     "cseInfo": {
      "$ref": "#/components/schemas/CseInfo"
     },
     "maxJoinedDevices": {
      "description": "Output only. The maximum number of devices that may be in the joined state simultaneously in this conference. This can be used by clients to guess whether it will be possible to join, but the only way to know is to try to join. It can also be used to inform users about the limit that is in effect. This limit is normally set when the conference is created and not changed during the lifetime of the conference. But there are some cases where it may change, so clients should be[...]",
      "format": "int32",
      "readOnly": true,
      "type": "integer"
     },
     "organizationName": {
      "description": "Output only. The name or description of the organization or domain that the organizer belongs to. The expected use of this in clients is to present messages like \"John Doe (outside of Google.com) is trying to join this call\", where \"Google.com\" is the organization name. The field will be empty if the organization name could not be determined, possibly because of a backend error.",
      "readOnly": true,
      "type": "string"
     },
     "paygateInfo": {
      "$ref": "#/components/schemas/PaygateInfo"
     },
     "presenter": {
      "$ref": "#/components/schemas/Presenter"
     },
     "recordingInfo": {
      "$ref": "#/components/schemas/RecordingInfo"
     },
     "recordingSessionInfo": {
      "$ref": "#/components/schemas/RecordingSessionInfo"
     },
     "settings": {
      "$ref": "#/components/schemas/CallSettings"
     },
     "streamingSessions": {
      "description": "Output only. Info about streaming sessions (recording or broadcast) for this conference. This should contain all active sessions. Currently, it's guaranteed to have at most one recording and at most one broadcast (at most two sessions in total). For each application type (recording or broadcast), latest inactive session is included if there's no active one.",
      "items": {
       "$ref": "#/components/schemas/StreamingSessionInfo"
      },
      "readOnly": true,
      "type": "array"
     },
     "transcriptionSessionInfo": {
      "$ref": "#/components/schemas/TranscriptionSessionInfo"
     },
     "viewerCount": {
      "description": "The number of devices viewing the conference - MeetingDevices that are in VIEWER role and JOINED state in the conference.",
      "format": "int32",
      "type": "integer"
     },
     "youTubeBroadcastSessionInfos": {
      "description": "Information about active YouTube broadcast sessions in the ongoing conference.",
      "items": {
       "$ref": "#/components/schemas/YouTubeBroadcastSessionInfo"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "CallSettings": {
    "description": "Effective settings of the ongoing conference.",
    "properties": {
     "accessLock": {
      "description": "Indicates whether the access lock is currently on or off.",
      "type": "boolean"
     },
     "accessType": {
      "description": "The current access type of the conference.",
      "enum": [
       "ACCESS_TYPE_UNSPECIFIED",
       "ACCESS_TYPE_OPEN",
       "ACCESS_TYPE_TRUSTED",
       "ACCESS_TYPE_RESTRICTED",
       "ACCESS_TYPE_CLOSED"
      ],
      "type": "string"
     },
     "allowJoiningBeforeHost": {
      "description": "Whether users can join this conference before a host (Host or Cohost).",
      "type": "boolean"
     },
     "attendanceReportEnabled": {
      "description": "Indicates whether the attendance report is currently enabled or disabled.",
      "type": "boolean"
     },
     "audioLock": {
      "description": "Indicates whether the audio lock is currently on or off.",
      "type": "boolean"
     },
     "chatLock": {
      "description": "Indicates whether the chat lock is currently on or off.",
      "type": "boolean"
     },
     "cseEnabled": {
      "description": "Whether Client-side Encryption is enabled for this conference.",
      "type": "boolean"
     },
     "moderationEnabled": {
      "description": "Indicates whether moderation is currently on or off.",
      "type": "boolean"
     },
     "presentLock": {
      "description": "Indicates whether the present lock is currently on or off.",
      "type": "boolean"
     },
     "reactionsLock": {
      "description": "Indicates whether the reactions lock is currently on or off.",
      "type": "boolean"
     },
     "videoLock": {
      "description": "Indicates whether the video lock is currently on or off.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "CapTokenHolderProto": {
    "description": "Represents a principal which possesses a particular secret string whose cryptographic hash is specified here. CapTokens (\"Capability Tokens\") are used in ACLProto. It's expected that ACLs with CapTokenHolders will strongly enforce them by Keystore-wrapping crypto keys for the corresponding CapTokens.",
    "properties": {
     "tokenHmacSha1Prefix": {
      "description": "The hash of the corresponding capability token. The value is defined to be identical to the one in acl.proto's CapTokenMetadata: 10-byte prefix of HMAC-SHA1 of the token. The HMAC key is the following fixed (non-secret) 512-bit value: 79b1c8f4 82baf523 b8a9ab4a e960f438 c45be041 11f1f222 e8a3f64d aeb05e3d c3576acc ec649194 aede422c 4e48e0d1 ff21234a a6ed6b49 a7fa592e efd7bba3",
      "format": "byte",
      "type": "string"
     }
    },
    "type": "object"
   },
   "Card": {
    "properties": {
     "cardActions": {
      "items": {
       "$ref": "#/components/schemas/CardAction"
      },
      "type": "array"
     },
     "displayStyle": {
      "enum": [
       "DISPLAY_STYLE_UNSPECIFIED",
       "PEEK",
       "REPLACE"
      ],
      "type": "string"
     },
     "fixedFooter": {
      "$ref": "#/components/schemas/FixedFooter"
     },
     "header": {
      "$ref": "#/components/schemas/CardHeader"
     },
     "name": {
      "description": "Name of the card used in CardNavigation.pop_to_card_name.",
      "type": "string"
     },
     "peekCardHeader": {
      "$ref": "#/components/schemas/CardHeader"
     },
     "sections": {
      "items": {
       "$ref": "#/components/schemas/Section"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "CardAction": {
    "description": "When an AddOn Card is shown in detailed view, a card action is the action associated with the card. For an invoice card, a typical action would be: delete invoice, email invoice or open the invoice in browser.",
    "properties": {
     "actionLabel": {
      "description": "The label used to be displayed in the action menu item.",
      "type": "string"
     },
     "onClick": {
      "$ref": "#/components/schemas/OnClick"
     }
    },
    "type": "object"
   },
   "CardCapabilityMetadata": {
    "properties": {
     "requiredCapabilities": {
      "description": "NEXT TAG : 2",
      "items": {
       "enum": [
        "UNKNOWN",
        "SUPPORTS_BASE_CARDS"
       ],
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "CardHeader": {
    "properties": {
     "imageAltText": {
      "description": "The alternative text of this image which will be used for accessibility.",
      "type": "string"
     },
     "imageStyle": {
      "enum": [
       "CROP_TYPE_NOT_SET",
       "SQUARE",
       "CIRCLE",
       "RECTANGLE_CUSTOM",
       "RECTANGLE_4_3"
      ],
      "type": "string"
     },
     "imageUrl": {
      "type": "string"
     },
     "subtitle": {
      "type": "string"
     },
     "title": {
      "description": "The title must be specified. The header has a fixed height: if both a title and subtitle is specified, each will take up 1 line. If only the title is specified, it will take up both lines. The header is rendered in collapsed and detailed view.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "CaribouAttributeValue": {
    "properties": {
     "booleanValue": {
      "description": "Tags 1 through 15 are reserved for the most commonly used fields.",
      "type": "boolean"
     },
     "intValue": {
      "format": "int32",
      "type": "integer"
     },
     "longValue": {
      "format": "int64",
      "type": "string"
     },
     "rawByteValue": {
      "description": "Generally, applications should avoid storing raw bytes and instead store structured data as protocol buffer extensions. This both reduces the amount of ad-hoc attribute parsing code as well as eliminates an intermediate copy of the data when deserializing the value. The rawByteValue field is mainly provided for compatibility with attributes stored before the introduction of the Attribute.Value.",
      "format": "byte",
      "type": "string"
     },
     "stringValue": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "ChatClientActionMarkup": {
    "description": "Actions handled by Chat Clients.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadata": {
    "description": "Metadata used as inputs to the localization that is performed on Dynamite-originated messages that are incompatible with Hangouts clients. See go/localization-of-system-messages for more details.",
    "properties": {
     "attachmentMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataAttachmentMetadata"
     },
     "botMessageMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataBotMessageMetadata"
     },
     "calendarEventMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataCalendarEventMetadata"
     },
     "deleteMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataDeleteMetadata"
     },
     "editMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataEditMetadata"
     },
     "spaceUrl": {
      "description": "The space URL embedded in the localized string.",
      "type": "string"
     },
     "tasksMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataTasksMetadata"
     },
     "videoCallMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadataVideoCallMetadata"
     }
    },
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataAttachmentMetadata": {
    "description": "An attachment uploaded in Dynamite and its filename.",
    "properties": {
     "filename": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataBotMessageMetadata": {
    "description": "A bot sent a message in Dynamite.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataCalendarEventMetadata": {
    "description": "A Calendar event message in Dynamite.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataDeleteMetadata": {
    "description": "A message was deleted in Dynamite.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataEditMetadata": {
    "description": "An edit was made in Dynamite.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataTasksMetadata": {
    "description": "A Tasks message in Dynamite.",
    "type": "object"
   },
   "ChatConserverDynamitePlaceholderMetadataVideoCallMetadata": {
    "description": "A Meet initiated in Dynamite and its URL.",
    "properties": {
     "meetingUrl": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "ChatConserverMessageContent": {
    "description": "The content of a chat message, which includes 0 or more segments along with 0 or more embeds, which represent various attachment types (like photos).",
    "properties": {
     "attachment": {
      "description": "Items attached to this message, such as photos. This should *NOT* be set by clients. It will be automatically set from media uploaded along with this request and using the information provided in existing_media.",
      "items": {
       "$ref": "#/components/schemas/SocialCommonAttachmentAttachment"
      },
      "type": "array"
     },
     "segment": {
      "description": "The text part of the message content. Segments are concatenated together to yield the full message. A message can have zero or more segments.",
      "items": {
       "$ref": "#/components/schemas/Segment"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "ChatContentExtension": {
    "description": "NEXT ID: 12",
    "properties": {
     "annotation": {
      "description": "Annotations to decorate this event.",
      "items": {
       "$ref": "#/components/schemas/EventAnnotation"
      },
      "type": "array"
     },
     "dynamitePlaceholderMetadata": {
      "$ref": "#/components/schemas/ChatConserverDynamitePlaceholderMetadata"
     },
     "eventOtrStatus": {
      "description": "Is this event OnTR or OffTR? Since some events can be ON_THE_RECORD and have an expiration_timestamp (for example enterprise retention users) we need to store the otr status.",
      "enum": [
       "OFF_THE_RECORD",
       "ON_THE_RECORD"
      ],
      "type": "string"
     },
     "groupLinkSharingModificationEvent": {
      "$ref": "#/components/schemas/GroupLinkSharingModificationEvent"
     },
     "hangoutEvent": {
      "$ref": "#/components/schemas/HangoutEvent"
     },
     "inviteAcceptedEvent": {
      "$ref": "#/components/schemas/InviteAcceptedEvent"
     },
     "membershipChangeEvent": {
      "$ref": "#/components/schemas/MembershipChangeEvent"
     },
     "otrChatMessageEvent": {
      "$ref": "#/components/schemas/OtrChatMessageEvent"
     },
     "otrModificationEvent": {
      "$ref": "#/components/schemas/OtrModificationEvent"
     },
     "renameEvent": {
      "$ref": "#/components/schemas/RenameEvent"
     }
    },
    "type": "object"
   },
   "ChatProto": {
    "description": "Represents the invitees or other users associated with a Babel Chat (see http://goto/babel). Corresponds to GroupType CHAT in //social/graph/storage/proto/data.proto.",
    "properties": {
     "chatId": {
      "description": "Chat IDs consist of alphanumeric characters and colons. Currently required.",
      "type": "string"
     },
     "memberType": {
      "description": "The type of Chat members to consider, e.g. \"all members\" vs. \"invitee\" These are defined by legacy_relation_id values in social.graph.storage.EdgeTypeEnum.EdgeType enum options in social/graph/storage/proto/id.proto. See chat.pb (defined in production/config/cdd/socialgraph/mixer_config/prod/node_type_config) for all valid edge types associated with chat. Currently required.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "CheckAccessResponse": {
    "properties": {
     "hasAccess": {
      "description": "Returns true if principal has access. Returns false otherwise.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "CircleProto": {
    "description": "Represents a Google+ Circle. Currently (12/2011), a Circle is identical to the ContactGroup with matching parameters, but Circle must only be used for true Circles and not other Focus groups, and should be preferred over ContactGroup where applicable. Soon it may become more efficient to check membership in a Circle than in a ContactGroup (see http://go/superglue). Support for this principal type is currently (12/2011) incomplete -- e.g., Keystore does not support it yet (see[...]",
    "properties": {
     "circleId": {
      "description": "Circle ID is unique only relative to the owner's Gaia ID. Currently required.",
      "format": "int64",
      "type": "string"
     },
     "ownerGaiaId": {
      "description": "The owner of the circle. Currently required.",
      "format": "int64",
      "type": "string"
     },
     "requiredConsistencyTimestampUsec": {
      "description": "If present, then tests for membership in this circle must use data known to be at least as fresh as the given (FBS-assigned) timestamp. See http://go/fbs-consistent-read-after-important-write Before using this, be sure that any service checking authorization against this circle supports checking consistency timestamps. For example, as of 12/2011, Keystore only supports this for the Moonshine configuration, and in others authorization checks will fail if the timestamp is pre[...]",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "ClientContext": {
    "description": "Represents the context of the client on behalf of which a HistoryRecord is produced. The ClientContext message can be used to hold context about the service client (e.g. the internal server making fusebox requests) or the user client (e.g. the IP address of the end user).",
    "properties": {
     "clientOperationId": {
      "description": "The client operation to which this history record belongs. The notion of a client operation is provided to keep track of client operations which might span multiple transactions in the lower level.",
      "type": "string"
     },
     "clientType": {
      "description": "E.g. \"pinto\", \"imap\", \"bigtop\", \"upload\"",
      "type": "string"
     },
     "sessionContext": {
      "$ref": "#/components/schemas/SessionContext"
     },
     "userIp": {
      "description": "Textual representation of the user's IP address, if available.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "CloudPrincipalProto": {
    "description": "Principal associated with a Cloud Principal representing third party user.",
    "properties": {
     "id": {
      "description": "Format: \"{identity-pool}:{subject}#\" Details: go/cloud-principal-identifiers",
      "type": "string"
     }
    },
    "type": "object"
   },
   "ClusterInfo": {
    "description": "ClusterInfo contains clustering related information for a particular thread that would be sent as part of the conversation view. Today, this information would be used by iOS notification server to identify whether the thread belongs to a cluster. If the thread belongs to a grouped cluster, it would identify whether the cluster is throttled.",
    "properties": {
     "clusterId": {
      "description": "IDs of the highest priority clusters to which the thread belongs to. If this field is not present, the thread does not belong to any cluster and would be shown in the inbox, unclustered.",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "throttled": {
      "description": "If the thread belongs to a grouped cluster and all of those clusters are throttled, then this field is set to true.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "CoActivity": {
    "description": "Metadata about a co-activity session.",
    "properties": {
     "activityTitle": {
      "description": "The title of the activity in this co-activity session. For example, this might be the title of the video being co-watched, or the name of the round of a game being co-played.",
      "type": "string"
     },
     "coActivityApp": {
      "description": "Identifies the app handling this co-activity.",
      "enum": [
       "CO_ACTIVITY_APP_UNSPECIFIED",
       "CO_ACTIVITY_APP_YOU_TUBE_MAIN",
       "CO_ACTIVITY_APP_SPOTIFY",
       "CO_ACTIVITY_APP_UNO",
       "CO_ACTIVITY_APP_HEADSUP",
       "CO_ACTIVITY_APP_KAHOOT",
       "CO_ACTIVITY_APP_GQUEUES",
       "CO_ACTIVITY_APP_YOU_TUBE_MUSIC",
       "CO_ACTIVITY_APP_SAMSUNG_NOTES",
       "CO_ACTIVITY_APP_HAPPY_AARDVARK"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "Collaboration": {
    "description": "Information about a collaboration session.",
    "properties": {
     "attachmentId": {
      "description": "The attachment being collaborated on.",
      "type": "string"
     },
     "initiator": {
      "$ref": "#/components/schemas/UserDisplayInfo"
     },
     "uri": {
      "description": "The uri of the artifact being collaborated on.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "Color": {
    "description": "Represents a color in the RGBA color space. This representation is designed for simplicity of conversion to/from color representations in various languages over compactness. For example, the fields of this representation can be trivially provided to the constructor of `java.awt.Color` in Java; it can also be trivially provided to UIColor's `+colorWithRed:green:blue:alpha` method in iOS; and, with just a little work, it can be easily formatted into a CSS `rgba()` string in Jav[...]",
    "properties": {
     "alpha": {
      "description": "The fraction of this color that should be applied to the pixel. That is, the final pixel color is defined by the equation: `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)` This means that a value of 1.0 corresponds to a solid color, whereas a value of 0.0 corresponds to a completely transparent color. This uses a wrapper message rather than a simple float scalar so that it is possible to distinguish between a default value and the value being unset.[...]",
      "format": "float",
      "type": "number"
     },
     "blue": {
      "description": "The amount of blue in the color as a value in the interval [0, 1].",
      "format": "float",
      "type": "number"
     },
     "green": {
      "description": "The amount of green in the color as a value in the interval [0, 1].",
      "format": "float",
      "type": "number"
     },
     "red": {
      "description": "The amount of red in the color as a value in the interval [0, 1].",
      "format": "float",
      "type": "number"
     }
    },
    "type": "object"
   },
   "CommunalLabelTag": {
    "description": "An individual instance (or \"tag\") of a label configured as a communal type that's associated with a message.",
    "properties": {
     "creatorUserId": {
      "description": "Gaia ID of the user who added the tag, if any. Not present for any tags automatically created by server-side processing.",
      "format": "int64",
      "type": "string"
     },
     "labelId": {
      "description": "A string ID representing the label. Possible ID values are documented at go/chat-labels-howto:ids. Example: \"^*t_p\" for \"Pinned\".",
      "type": "string"
     }
    },
    "type": "object"
   },
   "CompositeFilter": {
    "properties": {
     "logicOperator": {
      "description": "The logic operator of the sub filter.",
      "enum": [
       "AND",
       "OR",
       "NOT"
      ],
      "type": "string"
     },
     "subFilters": {
      "description": "Sub filters.",
      "items": {
       "$ref": "#/components/schemas/Filter"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "ConsentedAppUnfurlMetadata": {
    "description": "Annotation metadata app unfurl consent.",
    "properties": {
     "clientSpecifiedAppId": {
      "$ref": "#/components/schemas/UserId"
     }
    },
    "type": "object"
   },
   "ContactGroupProto": {
    "description": "A group of contacts for a given user, as described in http://cs/p#google3/focus/backend/proto/backend.proto Historically (and in still-existing ACLs), this was used to represent Google+ circles as well as contact groups, but this use is now deprecated. New code should use the CIRCLE principal type to represent Google+ circles.",
    "properties": {
     "groupId": {
      "description": "Group ID is unique only relative to the owner's Gaia ID.",
      "format": "int64",
      "type": "string"
     },
     "ownerGaiaId": {
      "format": "int64",
      "type": "string"
     },
     "requiredConsistencyTimestampUsec": {
      "description": "If present, then tests for membership in this ContactGroup must use data known to be at least as fresh as the given (FBS-assigned) timestamp. See http://go/fbs-consistent-read-after-important-write Before using this, be sure that any service checking authorization against this group supports checking consistency timestamps. For example, as of 12/2011, Keystore only supports this for the Moonshine configuration, and in others authorization checks will fail if the timestamp i[...]",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "ContentReport": {
    "properties": {
     "reportCreateTimestamp": {
      "description": "The time at which the report is generated. Always populated when it is in a response.",
      "format": "google-datetime",
      "type": "string"
     },
     "reportJustification": {
      "$ref": "#/components/schemas/ContentReportJustification"
     },
     "reportType": {
      "$ref": "#/components/schemas/AppsDynamiteSharedContentReportType"
     },
     "reporterUserId": {
      "$ref": "#/components/schemas/UserId"
     },
     "revisionCreateTimestamp": {
      "description": "Create timestamp of the revisions of the message when it's reported. Always populated when it is in a response.",
      "format": "google-datetime",
      "type": "string"
     }
    },
    "type": "object"
   },
   "ContentReportJustification": {
    "properties": {
     "userJustification": {
      "description": "Optional. User-generated free-text justification for the content report.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "ContentReportSummary": {
    "description": "Summarized info of content reports. Usually less expensive to fetch than to fetch all detailed reports. Set only when the request asks for it.",
    "properties": {
     "numberReports": {
      "description": "Total number of reports attached to this (revision of) message.",
      "format": "int32",
      "type": "integer"
     },
     "numberReportsAllRevisions": {
      "description": "Totoal number of reports attached to all revisions of this message (i.e. since creation). Set only when the request asks for it.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "ContextAttribute": {
    "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
    "properties": {
     "name": {
      "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched.",
      "type": "string"
     },
     "values": {
      "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched.",
      "items": {
       "type": "string"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "ContextualAddOnMarkup": {
    "description": "The markup for developers to specify the contents of a contextual AddOn. A contextual AddOn is triggered in context of an email. For that email, there can be N items that are associated with the email (e.g. contacts, sales lead, meeting information). Each item is represented as a \"card\". A card has two views, collapsed and detailed. If there are more than 1 card, the cards are show as a list of collapsed views. The end user can expand into the detailed view for each of thos[...]",
    "properties": {
     "cards": {
      "description": "A card must contain a header and at least 1 section.",
      "items": {
       "$ref": "#/components/schemas/Card"
      },
      "type": "array"
     },
     "toolbar": {
      "$ref": "#/components/schemas/Toolbar"
     }
    },
    "type": "object"
   },
   "CseInfo": {
    "description": "Information needed for Client-side Encryption.",
    "properties": {
     "cseDomain": {
      "description": "CSE domain name claimed by the meeting owner's company. This field is expected to be used for display purposes only, i.e., \"Extra encryption added by $cse_domain\". It can differ from the `cse_domain` as defined elsewhere on the User, in the case of cross-domain meetings.",
      "type": "string"
     },
     "wrappedKey": {
      "description": "The wrapped CSE key used by this conference.",
      "format": "byte",
      "type": "string"
     }
    },
    "type": "object"
   },
   "CustomEmojiMetadata": {
    "properties": {
     "customEmoji": {
      "$ref": "#/components/schemas/AppsDynamiteSharedCustomEmoji"
     }
    },
    "type": "object"
   },
   "CustomFunctionReturnValueMarkup": {
    "description": "The result of a user running a custom function.",
    "properties": {
     "errorMessage": {
      "description": "The error message to show to the user if something went wrong.",
      "type": "string"
     },
     "value": {
      "description": "The value that resulted from running the custom function."
     }
    },
    "type": "object"
   },
   "CustomerId": {
    "description": "Represents a GSuite customer ID. Obfuscated with CustomerIdObfuscator.",
    "properties": {
     "customerId": {
      "type": "string"
     }
    },
    "type": "object"
   },
   "CustomerIndexStats": {
    "description": "Aggregation of items by status code as of the specified date.",
    "properties": {
     "date": {
      "$ref": "#/components/schemas/Date"
     },
     "itemCountByStatus": {
      "description": "Number of items aggregrated by status code.",
      "items": {
       "$ref": "#/components/schemas/ItemCountByStatus"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "CustomerQueryStats": {
    "properties": {
     "date": {
      "$ref": "#/components/schemas/Date"
     },
     "queryCountByStatus": {
      "items": {
       "$ref": "#/components/schemas/QueryCountByStatus"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "CustomerSearchApplicationStats": {
    "description": "Search application stats for a customer for the given date.",
    "properties": {
     "count": {
      "description": "The count of search applications for the date.",
      "format": "int64",
      "type": "string"
     },
     "date": {
      "$ref": "#/components/schemas/Date"
     }
    },
    "type": "object"
   },
   "CustomerSessionStats": {
    "properties": {
     "date": {
      "$ref": "#/components/schemas/Date"
     },
     "searchSessionsCount": {
      "description": "The count of search sessions on the day",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "CustomerSettings": {
    "description": "Represents settings at a customer level.",
    "properties": {
     "auditLoggingSettings": {
      "$ref": "#/components/schemas/AuditLoggingSettings"
     },
     "vpcSettings": {
      "$ref": "#/components/schemas/VPCSettings"
     }
    },
    "type": "object"
   },
   "CustomerUserStats": {
    "properties": {
     "date": {
      "$ref": "#/components/schemas/Date"
     },
     "oneDayActiveUsersCount": {
      "description": "The count of unique active users in the past one day",
      "format": "int64",
      "type": "string"
     },
     "sevenDaysActiveUsersCount": {
      "description": "The count of unique active users in the past seven days",
      "format": "int64",
      "type": "string"
     },
     "thirtyDaysActiveUsersCount": {
      "description": "The count of unique active users in the past thirty days",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DataLossPreventionMetadata": {
    "description": "Annotation metadata for Data Loss Prevention that pertains to DLP violation on message send or edit events. It is used for client -> BE communication and other downstream process in BE (e.g. storage and audit logging), and it should never be returned to the client.",
    "properties": {
     "dlpScanSummary": {
      "$ref": "#/components/schemas/DlpScanSummary"
     },
     "warnAcknowledged": {
      "description": "Flag set by client on message resend to bypass WARN violation.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "DataSource": {
    "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search.",
    "properties": {
     "disableModifications": {
      "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data.",
      "type": "boolean"
     },
     "disableServing": {
      "description": "Disable serving any search or assist results.",
      "type": "boolean"
     },
     "displayName": {
      "description": "Required. Display name of the datasource The maximum length is 300 characters.",
      "type": "string"
     },
     "indexingServiceAccounts": {
      "description": "List of service accounts that have indexing access.",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "itemsVisibility": {
      "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility.",
      "items": {
       "$ref": "#/components/schemas/GSuitePrincipal"
      },
      "type": "array"
     },
     "name": {
      "description": "The name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource.",
      "type": "string"
     },
     "operationIds": {
      "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
      "items": {
       "type": "string"
      },
      "type": "array"
     },
     "returnThumbnailUrls": {
      "description": "Can a user request to get thumbnail URI for Items indexed in this data source.",
      "type": "boolean"
     },
     "shortName": {
      "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *<value>* then queries like *source:<value>* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, hangouts, gplus, keep, pe[...]",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DataSourceIndexStats": {
    "description": "Aggregation of items by status code as of the specified date.",
    "properties": {
     "date": {
      "$ref": "#/components/schemas/Date"
     },
     "itemCountByStatus": {
      "description": "Number of items aggregrated by status code.",
      "items": {
       "$ref": "#/components/schemas/ItemCountByStatus"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "DataSourceRestriction": {
    "description": "Restriction on Datasource.",
    "properties": {
     "filterOptions": {
      "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
      "items": {
       "$ref": "#/components/schemas/FilterOptions"
      },
      "type": "array"
     },
     "source": {
      "$ref": "#/components/schemas/Source"
     }
    },
    "type": "object"
   },
   "Date": {
    "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
    "properties": {
     "day": {
      "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
      "format": "int32",
      "type": "integer"
     },
     "month": {
      "description": "Month of date. Must be from 1 to 12.",
      "format": "int32",
      "type": "integer"
     },
     "year": {
      "description": "Year of date. Must be from 1 to 9999.",
      "format": "int32",
      "type": "integer"
     }
    },
    "type": "object"
   },
   "DateOperatorOptions": {
    "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
    "properties": {
     "greaterThanOperatorName": {
      "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:<value>* show results only where the value of the property named *closeDate* is later than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
      "type": "string"
     },
     "lessThanOperatorName": {
      "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:<value>* show results only where the value of the property named *closeDate* is earlier than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
      "type": "string"
     },
     "operatorName": {
      "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:<value>* show results only where the value of the *closeDate* property matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<val[...]",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DatePropertyOptions": {
    "description": "The options for date properties.",
    "properties": {
     "operatorOptions": {
      "$ref": "#/components/schemas/DateOperatorOptions"
     }
    },
    "type": "object"
   },
   "DateTimePicker": {
    "properties": {
     "label": {
      "description": "The label for the field, which is displayed to the user.",
      "type": "string"
     },
     "name": {
      "description": "The name of the text field which is used in FormInput, and uniquely identifies this input.",
      "type": "string"
     },
     "onChange": {
      "$ref": "#/components/schemas/FormAction"
     },
     "timezoneOffsetDate": {
      "description": "The number representing the time-zone offset from UTC, in minutes. If set, the value_ms_epoch will be displayed in the specified time zone. If not set, it will use the user's timezone setting in client side.",
      "format": "int32",
      "type": "integer"
     },
     "type": {
      "description": "The type of the DateTimePicker.",
      "enum": [
       "UNSPECIFIED_TYPE",
       "DATE_AND_TIME",
       "DATE_ONLY",
       "TIME_ONLY"
      ],
      "type": "string"
     },
     "valueMsEpoch": {
      "description": "The value to display which can be the default value before user input or previous user input. It is represented in milliseconds (Epoch time). - For DATE_AND_TIME type, the full epoch value is used. - For DATE_ONLY type, only date of the epoch time is used. - For TIME_ONLY type, only time of the epoch time is used. For example, you can set epoch time to 3 * 60 * 60 * 1000 to represent 3am.",
      "format": "int64",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DateValues": {
    "description": "List of date values.",
    "properties": {
     "values": {
      "items": {
       "$ref": "#/components/schemas/Date"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "DebugOptions": {
    "description": "Shared request debug options for all cloudsearch RPC methods.",
    "properties": {
     "enableDebugging": {
      "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
      "type": "boolean"
     }
    },
    "type": "object"
   },
   "DeepLinkData": {
    "description": "Deep-linking data is used to construct a deep-link URI for an activity or frame's embed, such that on click, the user is taken to the right place in a mobile app. If the app is not installed, the user is taken to the app store. If not on mobile, an analogous web uri is used.",
    "properties": {
     "appId": {
      "description": "Application ID (or project ID) from Google API Console.",
      "format": "int64",
      "type": "string"
     },
     "client": {
      "description": "The data for a Google API Console client is entered by a developer during client registration and is stored in PackagingService.",
      "items": {
       "$ref": "#/components/schemas/PackagingServiceClient"
      },
      "type": "array"
     },
     "deepLinkId": {
      "description": "The ID for non-URL content. Embeds may either have no analogous web presence or prefer a native mobile experience if supported. In the case of no web presence, instead of setting the \"url\" field of an embed, such developers will set this field and other content fields, e.g. thumbnail, title, description. If set, this field is used to construct the deep-link URI. Note that the native experience is preferred over the web link and the web link is used as a fallback.",
      "type": "string"
     },
     "url": {
      "description": "Analogous web presence. Used as desktop fallback or when no native link data is present.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DeleteMetadata": {
    "description": "A message delete in Dynamite inserts a Babel-only item containing this field. This is only inserted for messages before the source-of-truth flip. See go/hsc-message-deletions for more details.",
    "type": "object"
   },
   "DeleteQueueItemsRequest": {
    "properties": {
     "connectorName": {
      "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
      "type": "string"
     },
     "debugOptions": {
      "$ref": "#/components/schemas/DebugOptions"
     },
     "queue": {
      "description": "The name of a queue to delete items from.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DeliveryMedium": {
    "properties": {
     "mediumType": {
      "description": "Describes the medium the cent was sent/received. For example, if I receive an SMS via GV, the medium_type will be GV.",
      "enum": [
       "UNKNOWN_MEDIUM",
       "BABEL_MEDIUM",
       "GOOGLE_VOICE_MEDIUM",
       "LOCAL_SMS_MEDIUM"
      ],
      "type": "string"
     },
     "selfPhone": {
      "$ref": "#/components/schemas/VoicePhoneNumber"
     }
    },
    "type": "object"
   },
   "DisplayedProperty": {
    "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown.",
    "properties": {
     "propertyName": {
      "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "Divider": {
    "type": "object"
   },
   "DlpScanSummary": {
    "description": "A summary of a DLP scan event. This is a summary and should contain the minimum amount of data required to identify and process DLP scans. It is written to Starcast and encoded & returned to the client on attachment upload.",
    "properties": {
     "scanId": {
      "description": "The scan ID of the corresponding {@link DlpViolationScanRecord} in the {@link EphemeralDlpScans} Spanner table. This can be used to fetch additional details about the scan, e.g. for audit logging.",
      "type": "string"
     },
     "scanNotApplicableForContext": {
      "description": "Indicates that was no attempt to scan a message or attachment because it was not applicable in the given context (e.g. atomic mutuate). If this is true, scan_outcome should not be set. This flag is used to identify messages that DLP did not attempt to scan for monitoring scan coverage. Contents that DLP attempted to scan but skipped can be identified by DlpScanOutcome.SCAN_SKIPPED_* reasons. DEPRECATED: The prober can determine this from the context.",
      "type": "boolean"
     },
     "scanOutcome": {
      "description": "The outcome of a DLP Scan. If this is set, scan_not_applicable_for_context should not be true.",
      "enum": [
       "SCAN_UNKNOWN_OUTCOME",
       "SCAN_SUCCEEDED_NO_VIOLATION",
       "SCAN_SUCCEEDED_BLOCK",
       "SCAN_SUCCEEDED_WARN",
       "SCAN_SUCCEEDED_AUDIT_ONLY",
       "SCAN_FAILURE_EXCEPTION",
       "SCAN_FAILURE_RULE_FETCH_FAILED",
       "SCAN_FAILURE_TIMEOUT",
       "SCAN_FAILURE_ALL_RULES_FAILED",
       "SCAN_FAILURE_ILLEGAL_STATE_FOR_ATTACHMENTS",
       "SCAN_SKIPPED_EXPERIMENT_DISABLED",
       "SCAN_SKIPPED_CONSUMER",
       "SCAN_SKIPPED_NON_HUMAN_USER",
       "SCAN_SKIPPED_NO_MESSAGE",
       "SCAN_SKIPPED_USER_ACKNOWLEDGED_WARNING",
       "SCAN_SKIPPED_MESSAGE_FROM_UNSUPPORTED_ORIGIN",
       "SCAN_SKIPPED_MESSAGE_SENT_DURING_SPACE_MIGRATION",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_RULES_FOUND",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_APPLICABLE_RULES_FOR_ACTION_PARAMS",
       "SCAN_RULE_EVALUATION_SKIPPED_NO_APPLICABLE_RULES_FOR_TRIGGER",
       "SCAN_RULE_EVALUATION_SKIPPED_CHANGELING_PERMANENT_ERROR",
       "SCAN_RULE_EVALUATION_SKIPPED_CHANGELING_EMPTY_RESPONSE",
       "SCAN_RULE_EVALUATION_SKIPPED_UNSUPPORTED_FILE_TYPE",
       "SCAN_SUCCEEDED_WITH_FAILURES_NO_VIOLATION",
       "SCAN_SUCCEEDED_WITH_FAILURES_BLOCK",
       "SCAN_SUCCEEDED_WITH_FAILURES_WARN",
       "SCAN_SUCCEEDED_WITH_FAILURES_AUDIT_ONLY"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "DmId": {
    "properties": {
     "dmId": {
      "description": "Unique server assigned Id, per Direct Message Space.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DocumentInfo": {
    "description": "Information on a document attached to an active conference.",
    "properties": {
     "whiteboardInfo": {
      "$ref": "#/components/schemas/WhiteboardInfo"
     }
    },
    "type": "object"
   },
   "DoubleOperatorOptions": {
    "description": "Used to provide a search operator for double properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
    "properties": {
     "operatorName": {
      "description": "Indicates the operator name required in the query in order to use the double property in sorting or as a facet. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
      "type": "string"
     }
    },
    "type": "object"
   },
   "DoublePropertyOptions": {
    "description": "The options for double properties.",
    "properties": {
     "operatorOptions": {
      "$ref": "#/components/schemas/DoubleOperatorOptions"
     }
    },
    "type": "object"
   },
   "DoubleValues": {
    "description": "List of double values.",
    "properties": {
     "values": {
      "items": {
       "format": "double",
       "type": "number"
      },
      "type": "array"
     }
    },
    "type": "object"
   },
   "DriveClientActionMarkup": {
    "properties": {
     "requestFileScope": {
      "$ref": "#/components/schemas/RequestFileScope"
     }
    },
    "type": "object"
   },
   "DriveFollowUpRestrict": {
    "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\").",
    "properties": {
     "type": {
      "enum": [
       "UNSPECIFIED",
       "FOLLOWUP_SUGGESTIONS",
       "FOLLOWUP_ACTION_ITEMS"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "DriveLocationRestrict": {
    "description": "Drive location search restricts (e.g. \"is:starred\").",
    "properties": {
     "type": {
      "enum": [
       "UNSPECIFIED",
       "TRASHED",
       "STARRED"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "DriveMetadata": {
    "description": "Annotation metadata for Drive artifacts.",
    "properties": {
     "aclFixRequest": {
      "$ref": "#/components/schemas/AclFixRequest"
     },
     "aclFixStatus": {
      "$ref": "#/components/schemas/AclFixStatus"
     },
     "canEdit": {
      "description": "Can the current user edit this resource",
      "type": "boolean"
     },
     "canShare": {
      "description": "Can the current user share this resource",
      "type": "boolean"
     },
     "canView": {
      "description": "Can the current user view this resource",
      "type": "boolean"
     },
     "driveAction": {
      "description": "DriveAction for organizing this file in Drive. If the user does not have access to the Drive file, the value will be DriveAction.DRIVE_ACTION_UNSPECIFIED. This field is only set when part of a FileResult in a ListFilesResponse.",
      "enum": [
       "DRIVE_ACTION_UNSPECIFIED",
       "ADD_TO_DRIVE",
       "ORGANIZE",
       "ADD_SHORTCUT",
       "ADD_ANOTHER_SHORTCUT"
      ],
      "type": "string"
     },
     "driveState": {
      "enum": [
       "DRIVE_STATE_UNSPECIFIED",
       "IN_MY_DRIVE",
       "IN_TEAM_DRIVE",
       "SHARED_IN_DRIVE",
       "NOT_IN_DRIVE"
      ],
      "type": "string"
     },
     "embedUrl": {
      "$ref": "#/components/schemas/TrustedResourceUrlProto"
     },
     "encryptedDocId": {
      "description": "Indicates whether the Drive link contains an encrypted doc ID. If true, Dynamite should not attempt to query the doc ID in Drive Service. See go/docid-encryption for details.",
      "type": "boolean"
     },
     "encryptedResourceKey": {
      "description": "This is deprecated and unneeded. TODO (b/182479059): Remove this.",
      "type": "string"
     },
     "externalMimetype": {
      "description": "External mimetype of the Drive Resource (Useful for creating Drive URL) See: http://b/35219462",
      "type": "string"
     },
     "id": {
      "description": "Drive resource ID of the artifact.",
      "type": "string"
     },
     "isDownloadRestricted": {
      "description": "Deprecated. Whether the setting to restrict downloads is enabled for this file. This was previously used to determine whether to hide the download and print buttons in the UI, but is no longer used by clients, because Projector now independently queries Drive to ensure that we have the most up-to-date value.",
      "type": "boolean"
     },
     "isOwner": {
      "description": "If the current user is the Drive file's owner. The field is currently only set for Annotations for the ListFiles action (as opposed to fetching Topics/Messages with Drive annotations).",
      "type": "boolean"
     },
     "legacyUploadMetadata": {
      "$ref": "#/components/schemas/LegacyUploadMetadata"
     },
     "mimetype": {
      "description": "Mimetype of the Drive Resource",
      "type": "string"
     },
     "organizationDisplayName": {
      "description": "The display name of the organization owning the Drive item.",
      "type": "string"
     },
     "shortcutAuthorizedItemId": {
      "$ref": "#/components/schemas/AuthorizedItemId"
     },
     "shouldNotRender": {
      "description": "If this field is set to true, server should still contact external backends to get metadata for search but clients should not render this chip.",
      "type": "boolean"
     },
     "thumbnailHeight": {
      "description": "Thumbnail image of the Drive Resource",
      "format": "int32",
      "type": "integer"
     },
     "thumbnailUrl": {
      "description": "Thumbnail image of the Drive Resource",
      "type": "string"
     },
     "thumbnailWidth": {
      "description": "Thumbnail image of the Drive Resource",
      "format": "int32",
      "type": "integer"
     },
     "title": {
      "description": "Title of the Drive Resource",
      "type": "string"
     },
     "urlFragment": {
      "description": "Url string fragment that generally indicates the specific location in the linked file. Example: #header=h.123abc456. If the fragment is not present this will not be present and therefore default to an empty string. The \"#\" will not be included.",
      "type": "string"
     },
     "wrappedResourceKey": {
      "$ref": "#/components/schemas/WrappedResourceKey"
     }
    },
    "type": "object"
   },
   "DriveMimeTypeRestrict": {
    "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
    "properties": {
     "type": {
      "enum": [
       "UNSPECIFIED",
       "PDF",
       "DOCUMENT",
       "PRESENTATION",
       "SPREADSHEET",
       "FORM",
       "DRAWING",
       "SCRIPT",
       "MAP",
       "IMAGE",
       "AUDIO",
       "VIDEO",
       "FOLDER",
       "ARCHIVE",
       "SITE"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "DriveTimeSpanRestrict": {
    "description": "The time span search restrict (e.g. \"after:2017-09-11 before:2017-09-12\").",
    "properties": {
     "type": {
      "enum": [
       "UNSPECIFIED",
       "TODAY",
       "YESTERDAY",
       "LAST_7_DAYS",
       "LAST_30_DAYS",
       "LAST_90_DAYS"
      ],
      "type": "string"
     }
    },
    "type": "object"
   },
   "DynamiteMessagesScoringInfo": {
    "description": "This is the proto for holding message level scoring information. This data is used for logging in query-api server and for testing purposes.",
    "properties": {
     "commonContactCount": {
      "format": "int64",
      "type": "string"
     },
     "commonCountToContactListCountRatio": {
      "format": "double",
      "type": "number"
     },
     "commonCountToMembershipCountRatio": {
      "format": "double",
      "type": "number"
     },
     "creatorGaiaId": {
      "format": "int64",
      "type": "string"
     },
     "creatorInSearcherContactList": {
      "type": "boolean"
     },
     "crowdingMultiplier": {
      "format": "double",
      "type": "number"
     },
     "dasContactCount": {
      "format": "int64",
      "type": "string"
     },
     "finalScore": {
      "format": "double",
      "type": "number"
     },
     "freshnessScore": {
      "format": "double",
      "type": "number"
     },
     "joinedSpaceAffinityScore": {
[...]
