{
 "openapi": "3.0.1",
 "info": {
  "title": "Avaza API Documentation",
  "description": "Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization e[...]",
  "version": "v1"
 },
 "servers": [
  {
   "url": "https://api.avaza.com/"
  }
 ],
 "paths": {
  "/ScheduleSeries/AddBooking": {
   "post": {
    "tags": [
     "ScheduleSeries"
    ],
    "summary": "Create new Schedule Booking",
    "operationId": "ScheduleSeries_AddBooking",
    "security": [
     {
      "oauth2": [
       "write_schedule"
      ]
     }
    ]
   }
  },
  "/ScheduleSeries/AddLeave": {
   "post": {
    "tags": [
     "ScheduleSeries"
    ],
    "summary": "Create new Leave Booking",
    "operationId": "ScheduleSeries_AddLeave",
    "security": [
     {
      "oauth2": [
       "write_schedule"
      ]
     }
    ]
   }
  },
  "/ScheduleSeries/EditBooking": {
   "put": {
    "tags": [
     "ScheduleSeries"
    ],
    "summary": "Edit Booking",
    "operationId": "ScheduleSeries_EditBooking",
    "security": [
     {
      "oauth2": [
       "write_schedule"
      ]
     }
    ]
   }
  },
  "/ScheduleSeries/EditLeave": {
   "put": {
    "tags": [
     "ScheduleSeries"
    ],
    "summary": "Edit Leave Booking",
    "operationId": "ScheduleSeries_EditLeave",
    "security": [
     {
      "oauth2": [
       "write_schedule"
      ]
     }
    ]
   }
  },
  "/api/Account": {
   "get": {
    "tags": [
     "Account"
    ],
    "summary": "Account Details",
    "operationId": "Account_Get",
    "security": [
     {
      "oauth2": [
       "read_account"
      ]
     }
    ]
   }
  },
  "/api/Bill": {
   "get": {
    "tags": [
     "Bill"
    ],
    "summary": "Gets list of Bills",
    "description": "TransactionStatusCode values are: \"Draft\", \"Verified\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
    "operationId": "Bill_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Bill"
    ],
    "summary": "Create a new draft Bill",
    "operationId": "Bill_Post",
    "security": [
     {
      "oauth2": [
       "write_financials"
      ]
     }
    ]
   }
  },
  "/api/Bill/{id}": {
   "get": {
    "tags": [
     "Bill"
    ],
    "summary": "Gets a Bill by Bill ID",
    "operationId": "Bill_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/BillPayment": {
   "get": {
    "tags": [
     "BillPayment"
    ],
    "summary": "Gets list of Bill Payments",
    "operationId": "BillPayment_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "BillPayment"
    ],
    "summary": "Create new Bill Payment and optionally assign payment allocations to Bills",
    "operationId": "BillPayment_Post",
    "security": [
     {
      "oauth2": [
       "write_financials"
      ]
     }
    ]
   }
  },
  "/api/BillPayment/{id}": {
   "get": {
    "tags": [
     "BillPayment"
    ],
    "summary": "Gets a Bill Payment by Payment Transaction ID",
    "operationId": "BillPayment_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Company": {
   "get": {
    "tags": [
     "Company"
    ],
    "summary": "Gets list of Companies",
    "operationId": "Company_Get",
    "security": [
     {
      "oauth2": [
       "read_contacts"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Company"
    ],
    "summary": "Update a Company record.",
    "description": "Requires CompanyID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
    "operationId": "Company_Put",
    "security": [
     {
      "oauth2": [
       "write_contacts"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Company"
    ],
    "summary": "Create a Company",
    "operationId": "Company_Post",
    "security": [
     {
      "oauth2": [
       "write_contacts"
      ]
     }
    ]
   }
  },
  "/api/Company/Lookup": {
   "get": {
    "tags": [
     "Company"
    ],
    "summary": "Gets minimal list of Companies.",
    "description": "Certain roles see a restricted set of companies based on their project memberships",
    "operationId": "CompanyLookup",
    "security": [
     {
      "oauth2": [
       "read_contacts"
      ]
     }
    ]
   }
  },
  "/api/Company/{id}": {
   "get": {
    "tags": [
     "Company"
    ],
    "summary": "Gets Company by Company ID",
    "operationId": "Company_GetByID",
    "security": [
     {
      "oauth2": [
       "read_contacts"
      ]
     }
    ]
   }
  },
  "/api/Contact": {
   "get": {
    "tags": [
     "Contact"
    ],
    "summary": "Gets list of Contacts",
    "operationId": "Contact_Get",
    "security": [
     {
      "oauth2": [
       "read_contacts"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Contact"
    ],
    "summary": "Create a Contact",
    "operationId": "Contact_Post",
    "security": [
     {
      "oauth2": [
       "write_contacts"
      ]
     }
    ]
   }
  },
  "/api/Contact/{id}": {
   "get": {
    "tags": [
     "Contact"
    ],
    "summary": "Gets Contact by Contact ID",
    "operationId": "Contact_GetByID",
    "security": [
     {
      "oauth2": [
       "read_contacts"
      ]
     }
    ]
   }
  },
  "/api/CreditNote": {
   "get": {
    "tags": [
     "CreditNote"
    ],
    "summary": "Gets list of CreditNotes",
    "operationId": "CreditNote_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/CreditNote/{id}": {
   "get": {
    "tags": [
     "CreditNote"
    ],
    "summary": "Gets Credit Note by CreditNoteID",
    "operationId": "CreditNote_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Currency": {
   "get": {
    "tags": [
     "Currency"
    ],
    "summary": "Gets list of Currencies",
    "operationId": "Currency_Get"
   }
  },
  "/api/Estimate": {
   "get": {
    "tags": [
     "Estimate"
    ],
    "summary": "Gets list of Estimates",
    "description": "EstimateStatusCode values are: \"Draft\", \"Sent\", \"Accepted\", \"Converted\", \"Expired\", \"Rejected\"",
    "operationId": "Estimate_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Estimate"
    ],
    "summary": "Create a new draft Estimate",
    "operationId": "Estimate_Post",
    "security": [
     {
      "oauth2": [
       "write_financials"
      ]
     }
    ]
   }
  },
  "/api/Estimate/{id}": {
   "get": {
    "tags": [
     "Estimate"
    ],
    "summary": "Gets Estimate by Estimate ID",
    "operationId": "Estimate_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Expense": {
   "get": {
    "tags": [
     "Expense"
    ],
    "summary": "Gets list of Expenses",
    "operationId": "Expense_Get",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Expense"
    ],
    "summary": "Update an Expense",
    "description": "Update an Expense",
    "operationId": "Expense_Put",
    "security": [
     {
      "oauth2": [
       "write_expenses"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Expense"
    ],
    "summary": "Create an Expense",
    "description": "Create an Expense",
    "operationId": "Expense_Post",
    "security": [
     {
      "oauth2": [
       "write_expenses"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Expense"
    ],
    "summary": "Delete a Timesheet Entry",
    "operationId": "Expense_Delete",
    "security": [
     {
      "oauth2": [
       "write_expenses"
      ]
     }
    ]
   }
  },
  "/api/Expense/Attachment": {
   "post": {
    "tags": [
     "Expense"
    ],
    "operationId": "ExpenseAttachment",
    "security": [
     {
      "oauth2": [
       "write_expenses"
      ]
     }
    ]
   }
  },
  "/api/Expense/{id}": {
   "get": {
    "tags": [
     "Expense"
    ],
    "summary": "Gets an Expense Entry by Expense ID",
    "operationId": "Expense_GetByID",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpenseApproval/Submit": {
   "post": {
    "tags": [
     "Expense"
    ],
    "summary": "Submit Expenses for Approval.",
    "operationId": "ExpenseApproval",
    "security": [
     {
      "oauth2": [
       "write_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpenseCategory": {
   "get": {
    "tags": [
     "ExpenseCategory"
    ],
    "summary": "Gets list of Expense Categories",
    "description": "The default sort order is by Name asc",
    "operationId": "ExpenseCategory_Get",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpenseGroup/Lookup": {
   "get": {
    "tags": [
     "ExpenseGroup"
    ],
    "summary": "Gets minimal list of Expense Groups.",
    "description": "Expense Groups are for adhoc grouping of reported expenses. e.g. for expenses incurred on a Trip",
    "operationId": "ExpenseGroupLookup",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpenseMerchant/Lookup": {
   "get": {
    "tags": [
     "ExpenseMerchant"
    ],
    "summary": "Gets minimal list of Expense Merchants.",
    "operationId": "ExpenseMerchangeLookup",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpensePaymentMethod/Lookup": {
   "get": {
    "tags": [
     "ExpensePaymentMethod"
    ],
    "summary": "Gets minimal list of Expense Payment Methods.",
    "operationId": "ExpensePaymentMethodLookup",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/ExpenseSummary": {
   "get": {
    "tags": [
     "ExpenseSummary"
    ],
    "summary": "Gets Basic Summary of Expense Statistics",
    "operationId": "ExpenseSummary_Get",
    "security": [
     {
      "oauth2": [
       "read_expenses"
      ]
     }
    ]
   }
  },
  "/api/FixedAmount": {
   "get": {
    "tags": [
     "FixedAmount"
    ],
    "summary": "Gets list of Fixed Amounts",
    "operationId": "FixedAmount_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Inventory": {
   "get": {
    "tags": [
     "Inventory"
    ],
    "summary": "Gets list of Inventory",
    "operationId": "Inventory_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Inventory/{id}": {
   "get": {
    "tags": [
     "Inventory"
    ],
    "summary": "Gets InventoryItem by InventoryItem ID",
    "operationId": "Inventory_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Invoice": {
   "get": {
    "tags": [
     "Invoice"
    ],
    "summary": "Gets list of Invoices",
    "description": "TransactionStatusCode values are: \"Draft\", \"Sent\", \"Late\", \"Paid\", \"Partial\", \"Void\"",
    "operationId": "Invoice_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Invoice"
    ],
    "summary": "Create a new draft invoice",
    "operationId": "Invoice_Post",
    "security": [
     {
      "oauth2": [
       "write_financials"
      ]
     }
    ]
   }
  },
  "/api/Invoice/{id}": {
   "get": {
    "tags": [
     "Invoice"
    ],
    "summary": "Gets Invoice by Invoice ID",
    "operationId": "Invoice_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Payment": {
   "get": {
    "tags": [
     "Payment"
    ],
    "summary": "Gets list of Payments",
    "operationId": "Payment_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Payment"
    ],
    "summary": "Create new Payment and optionally assign payment allocations to Invoices",
    "operationId": "Payment_Post",
    "security": [
     {
      "oauth2": [
       "write_financials"
      ]
     }
    ]
   }
  },
  "/api/Payment/{id}": {
   "get": {
    "tags": [
     "Payment"
    ],
    "summary": "Gets Payment by Payment Transaction ID",
    "operationId": "Payment_GetByID",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Project": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Gets list of Projects",
    "operationId": "Project_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Project"
    ],
    "summary": "Update an Project",
    "description": "Update a Project",
    "operationId": "Project_Put",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Project"
    ],
    "summary": "Create a Project",
    "operationId": "Project_Post",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   }
  },
  "/api/Project/Lookup": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Gets minimal list of active Projects for the current user",
    "operationId": "ProjectLookup",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/Project/{id}": {
   "get": {
    "tags": [
     "Project"
    ],
    "summary": "Gets Project by Project ID",
    "operationId": "Project_GetByID",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/ProjectMember": {
   "get": {
    "tags": [
     "ProjectMember"
    ],
    "summary": "Gets list of Project Members",
    "description": "Include at least one of ProjectID or UserID parameters.",
    "operationId": "ProjectMember_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "ProjectMember"
    ],
    "summary": "Update a Member of a Project",
    "description": "Fields are only updated if their field name is in the FieldsToUpdate string collection. The Amount columns for Cost, Budget, Rates if specified should be a decimal. Financial amounts assume the currency of the parent Company. Budget units depend on the Budget method set on the Project.",
    "operationId": "ProjectMember_Put",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "ProjectMember"
    ],
    "summary": "Assign a user as a Member of a Project",
    "description": "the Amount columns for Cost, Budget, Rates should be specified as a decimal. Financial amounts assume the currency of the Customer company. Budget units depend on the Budget method set on the Project.",
    "operationId": "ProjectMember_Post",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   }
  },
  "/api/ProjectTimesheetCategory": {
   "get": {
    "tags": [
     "ProjectTimesheetCategory"
    ],
    "summary": "Gets list of Project Timesheet Categories",
    "description": "The default sort order is by isBillable desc, Name asc",
    "operationId": "ProjectTimesheetCategory_Get",
    "security": [
     {
      "oauth2": [
       "read_timesheets"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "ProjectTimesheetCategory"
    ],
    "summary": "Assign a TimeSheetCategory to a Project.",
    "operationId": "ProjectTimesheetCategory_Post",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   }
  },
  "/api/ScheduleAssignment": {
   "get": {
    "tags": [
     "ScheduleAssignment"
    ],
    "summary": "Gets list of Schedule Assignments.",
    "description": "Schedule assignments are per-day, and link to a parent Schedule Series.",
    "operationId": "ScheduleAssignment_Get",
    "security": [
     {
      "oauth2": [
       "read_schedule"
      ]
     }
    ]
   }
  },
  "/api/ScheduleSeries": {
   "get": {
    "tags": [
     "ScheduleSeries"
    ],
    "summary": "Gets list of Schedule Series",
    "description": "Schedule Series represents a strip of time assigned to a user over a date range, for a certain number of hours per day. They can be for Leave or for project work Bookings.",
    "operationId": "ScheduleSeries_Get",
    "security": [
     {
      "oauth2": [
       "read_schedule"
      ]
     }
    ]
   }
  },
  "/api/Section": {
   "get": {
    "tags": [
     "Section"
    ],
    "summary": "Gets list of Sections",
    "operationId": "Section_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Section"
    ],
    "summary": "Create a Section",
    "operationId": "Section_Post",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Section"
    ],
    "summary": "Delete a Section",
    "operationId": "Section_Delete",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   }
  },
  "/api/Task": {
   "get": {
    "tags": [
     "Task"
    ],
    "summary": "Gets list of Tasks",
    "operationId": "Task_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Task"
    ],
    "summary": "Update a Task.",
    "description": "Requires TaskID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.",
    "operationId": "Task_Put",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Task"
    ],
    "summary": "Create a Task",
    "operationId": "Task_Post",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Task"
    ],
    "summary": "Delete a Task",
    "operationId": "Task_Delete",
    "security": [
     {
      "oauth2": [
       "write_projects"
      ]
     }
    ]
   }
  },
  "/api/Task/Lookup": {
   "get": {
    "tags": [
     "Task"
    ],
    "summary": "Gets minimal list of Tasks for the current user",
    "description": "Groups Tasks by Section. Default sort is by Section Title followed by Task Title",
    "operationId": "TaskLookup",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/Task/{id}": {
   "get": {
    "tags": [
     "Task"
    ],
    "summary": "Gets Task by Task ID",
    "operationId": "Task_GetByID",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/TaskStatus": {
   "get": {
    "tags": [
     "TaskStatus"
    ],
    "summary": "Gets list of Task Statuses",
    "operationId": "TaskStatus_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/TaskType": {
   "get": {
    "tags": [
     "TaskType"
    ],
    "summary": "Gets list of Task Types",
    "operationId": "TaskType_Get",
    "security": [
     {
      "oauth2": [
       "read_projects"
      ]
     }
    ]
   }
  },
  "/api/Tax": {
   "get": {
    "tags": [
     "Tax"
    ],
    "summary": "Get List of Taxes configured in the Avaza account.",
    "operationId": "Tax_Get",
    "security": [
     {
      "oauth2": [
       "read_financials"
      ]
     }
    ]
   }
  },
  "/api/Timesheet": {
   "get": {
    "tags": [
     "Timesheet"
    ],
    "summary": "Gets list of Timsheets",
    "operationId": "Timesheet_Get",
    "security": [
     {
      "oauth2": [
       "read_timesheets"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Timesheet"
    ],
    "summary": "Update a Timesheet",
    "description": "The FieldsToUpdate field expects a string array collection of the field names you would like updated. Valid fields to update inlcude \"ProjectIDFK\", \"TimeSheetCategoryIDFK\", \"TaskIDFK\", \"Duration\", \"EntryDate\", \"Notes\", \"hasStartEndTime\", \"CustomMetadata\". If you intend to provide start/end times on timesheets, this is achieved by including the start time in the EntryDate field (Iso date format), along with a Duration (decimal format).",
    "operationId": "Timesheet_Put",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Timesheet"
    ],
    "summary": "Create a new Timesheet Entry",
    "operationId": "Timesheet_Post",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   }
  },
  "/api/Timesheet/{id}": {
   "get": {
    "tags": [
     "Timesheet"
    ],
    "summary": "Gets a Timesheet Entry by Timesheet ID",
    "operationId": "Timesheet_GetByID",
    "security": [
     {
      "oauth2": [
       "read_timesheets"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Timesheet"
    ],
    "summary": "Delete a Timesheet Entry",
    "operationId": "Timesheet_Delete",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   }
  },
  "/api/TimesheetSubmission": {
   "post": {
    "tags": [
     "TimesheetSubmission"
    ],
    "summary": "Submit Timesheets for Approval.",
    "description": "Either provide a a specific Day (WholeDayOf) or any day in a Week (WholeWeekOf) to submit all draft timesheets in that day or week",
    "operationId": "TimesheetSubmission_Post",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   }
  },
  "/api/TimesheetSummary": {
   "get": {
    "tags": [
     "TimesheetSummary"
    ],
    "summary": "Gets Basic Summary of Timesheet Statistics",
    "operationId": "TimesheetSummary_Get",
    "security": [
     {
      "oauth2": [
       "read_timesheets"
      ]
     }
    ]
   }
  },
  "/api/TimesheetTimer": {
   "get": {
    "tags": [
     "TimesheetTimer"
    ],
    "summary": "Gets the  Running Timer if there is one for a user.",
    "operationId": "TimesheetTimer_GetRunningTimer",
    "security": [
     {
      "oauth2": [
       "read_timesheets"
      ]
     }
    ]
   }
  },
  "/api/TimesheetTimer/{id}": {
   "post": {
    "tags": [
     "TimesheetTimer"
    ],
    "summary": "Starts a Timer running on an existing Timesheet Entry",
    "operationId": "TimesheetTimer_StartTimer",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "TimesheetTimer"
    ],
    "summary": "Stop the timer running on an existing Timesheet Entry",
    "operationId": "TimesheetTimer_StopTimer",
    "security": [
     {
      "oauth2": [
       "write_timesheets"
      ]
     }
    ]
   }
  },
  "/api/UserProfile": {
   "get": {
    "tags": [
     "UserProfile"
    ],
    "summary": "Get Collection of Users who have roles in the current Avaza account.",
    "description": "Admin and Invoice Managers can see all. Other users are limited to seeing their own profile.",
    "operationId": "UserProfile_Get",
    "security": [
     {
      "oauth2": [
       "read_users"
      ]
     }
    ]
   }
  },
  "/api/Webhook": {
   "get": {
    "tags": [
     "Webhook"
    ],
    "summary": "Get list of Webhook Subscriptions",
    "operationId": "Webhook_Get",
    "security": [
     {
      "oauth2": [
       "webhook_notifications"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Webhook"
    ],
    "summary": "Subscribe to Webhook. On success, returns ID of webhook subscription.",
    "description": "When you receive a webhook, you should respond with Http 200 OK Status Code, otherwise we will retry. To create a webhook, you need both the webhook_notifications scope, as well as the scope for the required entity being monitored.  Event values are: \"company_created\", \"company_deleted\", \"company_updated\", \"contact_created\", \"contact_deleted\", \"contact_updated\", \"invoice_created\", \"invoice_sent\",\"invoice_updated\",\"invoice_deleted\", \"project_created\", \"p[...]",
    "operationId": "Webhook_Post",
    "security": [
     {
      "oauth2": [
       "webhook_notifications",
       "read_contacts",
       "read_account",
       "read_users",
       "read_financials",
       "read_projects",
       "read_schedule",
       "read_timesheets",
       "read_expenses",
       "write_contacts",
       "write_account",
       "write_users",
       "write_financials",
       "write_projects",
       "write_schedule",
       "write_timesheets",
       "write_expenses"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Webhook"
    ],
    "summary": "Delete webhook subscription by URL",
    "operationId": "Webhook_DeleteByUrl",
    "security": [
     {
      "oauth2": [
       "webhook_notifications"
      ]
     }
    ]
   }
  },
  "/api/Webhook/{id}": {
   "get": {
    "tags": [
     "Webhook"
    ],
    "summary": "Get Webhook Subscription by SubscriptionID",
    "operationId": "Webhook_GetByID",
    "security": [
     {
      "oauth2": [
       "webhook_notifications"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Webhook"
    ],
    "summary": "Delete Webhook Subscription by ID",
    "operationId": "Webhook_Delete",
    "security": [
     {
      "oauth2": [
       "webhook_notifications"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "oauth2": {
    "type": "oauth2",
    "description": "OAuth2 Implicit Grant"
   }
  }
 }
}