{
 "openapi": "3.0.0",
 "servers": [
  {
   "url": "https://slides.googleapis.com/"
  }
 ],
 "info": {
  "contact": {
   "name": "Google",
   "url": "https://google.com",
   "x-twitter": "youtube"
  },
  "description": "Reads and writes Google Slides presentations.",
  "license": {
   "name": "Creative Commons Attribution 3.0",
   "url": "http://creativecommons.org/licenses/by/3.0/"
  },
  "termsOfService": "https://developers.google.com/terms/",
  "title": "Google Slides API",
  "version": "v1",
  "x-apiClientRegistration": {
   "url": "https://console.developers.google.com"
  },
  "x-apisguru-categories": [
   "analytics",
   "media"
  ],
  "x-logo": {
   "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
  },
  "x-origin": [
   {
    "converter": {
     "url": "https://github.com/mermade/oas-kit",
     "version": "7.0.4"
    },
    "format": "google",
    "url": "https://slides.googleapis.com/$discovery/rest?version=v1",
    "version": "v1"
   }
  ],
  "x-providerName": "googleapis.com",
  "x-serviceName": "slides"
 },
 "tags": [
  {
   "name": "presentations"
  }
 ],
 "paths": {
  "/v1/presentations": {
   "post": {
    "description": "Creates a blank presentation using the title given in the request. If a `presentationId` is provided, it is used as the ID of the new presentation. Otherwise, a new ID is generated. Other fields in the request, including any provided content, are ignored. Returns the created presentation.",
    "operationId": "slides.presentations.create",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.file"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations"
      ]
     }
    ],
    "tags": [
     "presentations"
    ]
   }
  },
  "/v1/presentations/{presentationId}": {
   "get": {
    "description": "Gets the latest version of the specified presentation.",
    "operationId": "slides.presentations.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.file"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.readonly"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ]
     }
    ],
    "tags": [
     "presentations"
    ]
   }
  },
  "/v1/presentations/{presentationId}/pages/{pageObjectId}": {
   "get": {
    "description": "Gets the latest version of the specified page in the presentation.",
    "operationId": "slides.presentations.pages.get",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.file"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.readonly"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ]
     }
    ],
    "tags": [
     "presentations"
    ]
   }
  },
  "/v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail": {
   "get": {
    "description": "Generates a thumbnail of the latest version of the specified page in the presentation and returns a URL to the thumbnail image. This request counts as an [expensive read request](/slides/limits) for quota purposes.",
    "operationId": "slides.presentations.pages.getThumbnail",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.file"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.readonly"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations.readonly"
      ]
     }
    ],
    "tags": [
     "presentations"
    ]
   }
  },
  "/v1/presentations/{presentationId}:batchUpdate": {
   "post": {
    "description": "Applies one or more updates to the presentation. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only th[...]",
    "operationId": "slides.presentations.batchUpdate",
    "security": [
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.file"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/drive.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/drive.readonly"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/presentations"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/presentations"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "Oauth2": [
       "https://www.googleapis.com/auth/spreadsheets.readonly"
      ],
      "Oauth2c": [
       "https://www.googleapis.com/auth/spreadsheets.readonly"
      ]
     }
    ],
    "tags": [
     "presentations"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "Oauth2": {
    "description": "Oauth 2.0 implicit authentication",
    "type": "oauth2"
   },
   "Oauth2c": {
    "description": "Oauth 2.0 authorizationCode authentication",
    "type": "oauth2"
   }
  }
 }
}