{
 "openapi": "3.0.1",
 "info": {
  "title": "Netatmo",
  "description": "<h3>Welcome to the Netatmo swagger on-line documentation !</h3>\nThis site is a complement to the official <a href=\"https://dev.netatmo.com/\">Netatmo developper documentation</a> using swagger to bring interactivity and easy testing of requests with the \"try it\" button (authenticate with the authorization code OAuth2 flow by clicking the authenticate button in the methods). You can find the source code for this site can be found in the project <a href=\"https://github.com/c[...]",
  "termsOfService": "https://dev.netatmo.com/dev/resources/legal/introduction",
  "contact": {
   "name": "Netatmo",
   "email": "contact-api@netatmo.com"
  },
  "license": {
   "name": "Netatmo : Terms of Service",
   "url": "https://dev.netatmo.com/dev/resources/legal/introduction"
  },
  "version": "1.1.5"
 },
 "servers": [
  {
   "url": "https://api.netatmo.net/api"
  }
 ],
 "tags": [
  {
   "name": "station",
   "description": "Weather station specific methods"
  },
  {
   "name": "healthyhomecoach",
   "description": "Healthy Home Coach specific methods"
  },
  {
   "name": "thermostat",
   "description": "Thermostat specific methods"
  },
  {
   "name": "welcome",
   "description": "Welcome specific methods"
  },
  {
   "name": "public",
   "description": "Public stations specific methods"
  },
  {
   "name": "partner",
   "description": "Partner API specific methods"
  },
  {
   "name": "deprecated",
   "description": "These methods are no longer maintained nor supported"
  }
 ],
 "paths": {
  "/addwebhook": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Links a callback url to a user.\n",
    "operationId": "addwebhook",
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/createnewschedule": {
   "post": {
    "tags": [
     "thermostat"
    ],
    "description": "The method createnewschedule creates a new schedule stored in the backup list.",
    "operationId": "createnewschedule",
    "security": [
     {
      "code_oauth": [
       "write_thermostat"
      ]
     },
     {
      "password_oauth": [
       "write_thermostat"
      ]
     }
    ]
   }
  },
  "/devicelist": {
   "get": {
    "tags": [
     "deprecated"
    ],
    "description": "The method devicelist returns the list of devices owned by the user, and their modules.\nA device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.\n",
    "operationId": "devicelist",
    "deprecated": true,
    "security": [
     {
      "code_oauth": [
       "read_thermostat",
       "read_station"
      ]
     },
     {
      "password_oauth": [
       "read_thermostat",
       "read_station"
      ]
     }
    ]
   }
  },
  "/dropwebhook": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Dissociates a webhook from a user.\n",
    "operationId": "dropwebhook",
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/getcamerapicture": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Returns the snapshot associated to an event.\n",
    "operationId": "getcamerapicture",
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/geteventsuntil": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Returns the snapshot associated to an event.\n",
    "operationId": "geteventsuntil",
    "security": [
     {
      "code_oauth": [
       "access_camera",
       "read_camera"
      ]
     },
     {
      "password_oauth": [
       "access_camera",
       "read_camera"
      ]
     }
    ]
   }
  },
  "/gethomecoachsdata": {
   "get": {
    "tags": [
     "healthyhomecoach"
    ],
    "description": "The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).",
    "operationId": "gethomecoachsdata",
    "security": [
     {
      "code_oauth": [
       "read_homecoach"
      ]
     },
     {
      "password_oauth": [
       "read_homecoach"
      ]
     }
    ]
   }
  },
  "/gethomedata": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Returns information about users homes and cameras.\n",
    "operationId": "gethomedata",
    "security": [
     {
      "code_oauth": [
       "access_camera",
       "read_camera"
      ]
     },
     {
      "password_oauth": [
       "access_camera",
       "read_camera"
      ]
     }
    ]
   }
  },
  "/getlasteventof": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Returns most recent events.\n",
    "operationId": "getlasteventof",
    "security": [
     {
      "code_oauth": [
       "access_camera",
       "read_camera"
      ]
     },
     {
      "password_oauth": [
       "access_camera",
       "read_camera"
      ]
     }
    ]
   }
  },
  "/getmeasure": {
   "get": {
    "tags": [
     "station",
     "thermostat",
     "partner",
     "public"
    ],
    "description": "The method getmeasure returns the measurements of a device or a module.\n",
    "operationId": "getmeasure",
    "security": [
     {
      "code_oauth": [
       "read_thermostat",
       "read_station"
      ]
     },
     {
      "password_oauth": [
       "read_thermostat",
       "read_station"
      ]
     }
    ]
   }
  },
  "/getnextevents": {
   "get": {
    "tags": [
     "welcome"
    ],
    "description": "Returns previous events.\n",
    "operationId": "getnextevents",
    "security": [
     {
      "code_oauth": [
       "access_camera",
       "read_camera"
      ]
     },
     {
      "password_oauth": [
       "access_camera",
       "read_camera"
      ]
     }
    ]
   }
  },
  "/getpublicdata": {
   "get": {
    "tags": [
     "public"
    ],
    "description": "Retrieves publicly shared weather data from Outdoor Modules within a predefined area.",
    "operationId": "getpublicdata",
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/getstationsdata": {
   "get": {
    "tags": [
     "station"
    ],
    "description": "The method getstationsdata Returns data from a user's Weather Stations (measures and device specific data).",
    "operationId": "getstationsdata",
    "security": [
     {
      "code_oauth": [
       "read_station"
      ]
     },
     {
      "password_oauth": [
       "read_station"
      ]
     }
    ]
   }
  },
  "/getthermostatsdata": {
   "get": {
    "tags": [
     "thermostat"
    ],
    "description": "The method getthermostatsdata returns information about user's thermostats such as their last measurements.",
    "operationId": "getthermostatsdata",
    "security": [
     {
      "code_oauth": [
       "read_thermostat"
      ]
     },
     {
      "password_oauth": [
       "read_thermostat"
      ]
     }
    ]
   }
  },
  "/getthermstate": {
   "get": {
    "tags": [
     "deprecated"
    ],
    "description": "The method getthermstate returns the last Thermostat measurements, its current weekly schedule, and, if present, its current manual temperature setpoint.",
    "operationId": "getthermstate",
    "deprecated": true,
    "security": [
     {
      "code_oauth": [
       "read_thermostat"
      ]
     },
     {
      "password_oauth": [
       "read_thermostat"
      ]
     }
    ]
   }
  },
  "/getuser": {
   "get": {
    "tags": [
     "deprecated"
    ],
    "description": "The method getuser returns information about a user such as prefered language, prefered units, and list of devices.\n",
    "operationId": "getuser",
    "deprecated": true,
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/partnerdevices": {
   "get": {
    "tags": [
     "partner"
    ],
    "description": "The method partnerdevices returns the list of device_id to which your partner application has access to.",
    "operationId": "partnerdevices",
    "security": [
     {
      "code_oauth": null
     },
     {
      "password_oauth": null
     }
    ]
   }
  },
  "/setpersonsaway": {
   "post": {
    "tags": [
     "welcome"
    ],
    "description": "Sets a person as 'Away' or the Home as 'Empty'. The event will be added to the user’s timeline.\n",
    "operationId": "setpersonsaway",
    "security": [
     {
      "code_oauth": [
       "write_camera"
      ]
     },
     {
      "password_oauth": [
       "write_camera"
      ]
     }
    ]
   }
  },
  "/setpersonshome": {
   "post": {
    "tags": [
     "welcome"
    ],
    "description": "Sets a person as 'At home'.\n",
    "operationId": "setpersonshome",
    "security": [
     {
      "code_oauth": [
       "write_camera"
      ]
     },
     {
      "password_oauth": [
       "write_camera"
      ]
     }
    ]
   }
  },
  "/setthermpoint": {
   "post": {
    "tags": [
     "thermostat"
    ],
    "description": "The method setthermpoint changes the Thermostat manual temperature setpoint.",
    "operationId": "setthermpoint",
    "security": [
     {
      "code_oauth": [
       "write_thermostat"
      ]
     },
     {
      "password_oauth": [
       "write_thermostat"
      ]
     }
    ]
   }
  },
  "/switchschedule": {
   "post": {
    "tags": [
     "thermostat"
    ],
    "description": "The method switchschedule switches the Thermostat's schedule to another existing schedule.",
    "operationId": "switchschedule",
    "security": [
     {
      "code_oauth": [
       "write_thermostat"
      ]
     },
     {
      "password_oauth": [
       "write_thermostat"
      ]
     }
    ]
   }
  },
  "/syncschedule": {
   "post": {
    "tags": [
     "thermostat"
    ],
    "description": "The method syncschedule changes the Thermostat weekly schedule.",
    "operationId": "syncschedule",
    "security": [
     {
      "code_oauth": [
       "write_thermostat"
      ]
     },
     {
      "password_oauth": [
       "write_thermostat"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "code_oauth": {
    "type": "oauth2"
   },
   "password_oauth": {
    "type": "oauth2"
   }
  }
 }
}